"""Domain-organised view exports for the common app."""

from .auth import (
    CustomLoginView,
    CustomLogoutView,
    UserRegistrationView,
    page_restricted,
    profile,
)
from .redirects import (
    DeprecatedRedirectView,
    StaffTaskRedirectView,
    ProjectWorkflowRedirectView,
    EventRedirectView,
)
from .deprecation import (
    deprecation_dashboard,
)
from .calendar_resources import (
    resource_list,
    resource_create,
    resource_detail,
    resource_edit,
    resource_delete,
    resource_calendar,
    booking_request,
    booking_approve,
    booking_list,
    staff_leave_request,
    staff_leave_list,
    staff_leave_approve,
)
from .calendar_preferences import calendar_preferences
from .calendar_sharing import (
    calendar_share_create,
    calendar_share_manage,
    calendar_share_view,
    calendar_share_toggle,
    calendar_share_delete,
)
from .attendance import (
    event_check_in,
    event_generate_qr,
    event_scan_qr,
    event_attendance_report,
)
from .calendar_api import (
    calendar_event_update,
)
from .calendar import (
    work_items_calendar_feed,
    work_item_modal,
)
# Alias for unified calendar feed (used by URL name)
work_items_feed = work_items_calendar_feed
from .work_items import (
    work_item_list,
    work_item_detail,
    work_item_create,
    work_item_edit,
    work_item_delete,
    work_item_delete_modal,
    work_item_tree_partial,
    work_item_update_progress,
    work_item_calendar_feed,
    work_item_sidebar_detail,
    work_item_sidebar_edit,
    work_item_sidebar_create,
    work_item_duplicate,
)

# Import task_detail for calendar integration
# from .tasks import task_detail  # Commented out - function does not exist
from .communities import (
    communities_add,
    communities_add_municipality,
    communities_add_province,
    communities_delete,
    communities_delete_municipal,
    communities_delete_provincial,
    communities_restore,
    communities_restore_municipal,
    communities_restore_provincial,
    communities_view,
    communities_view_municipal,
    communities_view_provincial,
    communities_home,
    communities_manage,
    communities_manage_municipal,
    communities_manage_provincial,
    communities_stakeholders,
    communities_edit,
    communities_edit_municipal,
    communities_edit_provincial,
    communities_submit_provincial,
    location_centroid,
)
from .coordination import (
    coordination_events,
    coordination_calendar,
    coordination_home,
    coordination_organizations,
    coordination_partnerships,
    coordination_view_all,
    event_create,  # Defined in coordination.py, redirects to WorkItem
    coordination_activity_create,
    organization_create,
    organization_delete,
    organization_detail,
    organization_edit,
    partnership_create,
    partnership_detail,
    partnership_update,
    partnership_delete,
)
from .dashboard import (
    dashboard,
    dashboard_stats_cards,
    dashboard_metrics,
    dashboard_activity,
    dashboard_alerts,
)
from .management import (
    oobc_management_home,
    oobc_calendar,
    oobc_calendar_modern,
    oobc_calendar_advanced_modern,
    oobc_calendar_feed_json,
    oobc_calendar_feed_ics,
    oobc_calendar_brief,
    planning_budgeting,
    gap_analysis_dashboard,
    policy_budget_matrix,
    mao_focal_persons_registry,
    community_needs_summary,
    community_need_submit,
    community_voting_browse,
    community_voting_vote,
    community_voting_results,
    budget_feedback_dashboard,
    submit_service_feedback,
    transparency_dashboard,
    strategic_goals_dashboard,
    annual_planning_dashboard,
    regional_development_alignment,
    scenario_list,
    scenario_create,
    scenario_detail,
    scenario_compare,
    scenario_optimize,
    analytics_dashboard,
    budget_forecasting,
    trend_analysis,
    impact_assessment,
    staff_management,
    staff_task_board,
    staff_task_modal_create,
    staff_task_modal,
    staff_task_delete,
    staff_task_inline_update,
    staff_task_update,
    staff_task_update_field,
    staff_task_create,
    staff_task_create_api,
    staff_api_assignees,
    staff_api_teams,
    staff_profiles_list,
    staff_profile_create,
    staff_profile_update,
    staff_profiles_detail,
    staff_profile_delete,
    staff_performance_dashboard,
    staff_training_development,
    staff_team_assign,
    staff_team_manage,
    user_approvals,
    user_approval_action,
)
# Legacy tasks.py imports removed - use WorkItem views instead
# from .tasks import (
#     tasks_by_domain,
#     assessment_tasks,
#     event_tasks,
#     policy_tasks,
#     ppa_tasks,
#     service_tasks,
#     enhanced_task_dashboard,
#     task_analytics,
#     domain_task_analytics,
#     task_template_list,
#     task_template_detail,
#     instantiate_template,
#     task_complete,
#     task_start,
#     task_assign,
# )
from .mana import (
    mana_assessment_delete,
    mana_assessment_detail,
    mana_assessment_edit,
    mana_desk_review,
    mana_geographic_data,
    mana_home,
    mana_stats_cards,
    mana_playbook,
    mana_activity_log,
    mana_activity_planner,
    mana_activity_processing,
    mana_key_informant_interviews,
    mana_manage_assessments,
    mana_new_assessment,
    mana_provincial_overview,
    mana_provincial_card_detail,
    mana_province_edit,
    mana_province_delete,
    mana_regional_overview,
    mana_survey_module,
)
from .recommendations import (
    recommendations_by_area,
    recommendations_home,
    recommendations_manage,
    recommendations_new,
    recommendations_create,
    recommendations_autosave,
    recommendations_programs,
    recommendations_services,
    recommendations_view,
    recommendations_edit,
    recommendations_delete,
    recommendations_stats_cards,
)

__all__ = [
    "CustomLoginView",
    "CustomLogoutView",
    "UserRegistrationView",
    "profile",
    "page_restricted",
    "dashboard",
    "dashboard_stats_cards",
    "dashboard_metrics",
    "dashboard_activity",
    "dashboard_alerts",
    "resource_list",
    "resource_create",
    "resource_detail",
    "resource_edit",
    "resource_delete",
    "resource_calendar",
    "booking_request",
    "booking_approve",
    "booking_list",
    "staff_leave_request",
    "staff_leave_list",
    "staff_leave_approve",
    "oobc_management_home",
    "oobc_calendar",
    "oobc_calendar_modern",
    "oobc_calendar_advanced_modern",
    "oobc_calendar_feed_json",
    "oobc_calendar_feed_ics",
    "oobc_calendar_brief",
    "planning_budgeting",
    "gap_analysis_dashboard",
    "policy_budget_matrix",
    "mao_focal_persons_registry",
    "community_needs_summary",
    "community_need_submit",
    "community_voting_browse",
    "community_voting_vote",
    "community_voting_results",
    "budget_feedback_dashboard",
    "submit_service_feedback",
    "transparency_dashboard",
    "strategic_goals_dashboard",
    "annual_planning_dashboard",
    "regional_development_alignment",
    "scenario_list",
    "scenario_create",
    "scenario_detail",
    "scenario_compare",
    "scenario_optimize",
    "analytics_dashboard",
    "budget_forecasting",
    "trend_analysis",
    "impact_assessment",
    "staff_management",
    "staff_task_board",
    "staff_task_modal_create",
    "staff_task_modal",
    "staff_task_delete",
    "staff_task_inline_update",
    "staff_task_update",
    "staff_task_update_field",
    "staff_task_create",
    "staff_task_create_api",
    "staff_api_assignees",
    "staff_api_teams",
    "staff_profiles_list",
    "staff_profile_create",
    "staff_profile_update",
    "staff_profiles_detail",
    "staff_profile_delete",
    "staff_performance_dashboard",
    "staff_training_development",
    "staff_team_assign",
    "staff_team_manage",
    "user_approvals",
    "user_approval_action",
    "communities_home",
    "communities_add",
    "communities_add_municipality",
    "communities_add_province",
    "communities_view",
    "communities_view_municipal",
    "communities_view_provincial",
    "communities_manage",
    "communities_manage_municipal",
    "communities_manage_provincial",
    "communities_edit",
    "communities_edit_municipal",
    "communities_edit_provincial",
    "communities_submit_provincial",
    "communities_delete",
    "communities_delete_municipal",
    "communities_delete_provincial",
    "communities_restore",
    "communities_restore_municipal",
    "communities_restore_provincial",
    "communities_stakeholders",
    "location_centroid",
    "mana_home",
    "mana_stats_cards",
    "mana_new_assessment",
    "mana_manage_assessments",
    "mana_assessment_delete",
    "mana_assessment_detail",
    "mana_assessment_edit",
    "mana_regional_overview",
    "mana_provincial_overview",
    "mana_provincial_card_detail",
    "mana_province_edit",
    "mana_province_delete",
    "mana_desk_review",
    "mana_survey_module",
    "mana_key_informant_interviews",
    "mana_activity_planner",
    "mana_activity_log",
    "mana_activity_processing",
    "mana_playbook",
    "mana_geographic_data",
    "coordination_home",
    "coordination_organizations",
    "coordination_partnerships",
    "coordination_events",
    "coordination_calendar",
    "coordination_view_all",
    "event_create",
    "coordination_activity_create",
    "organization_create",
    "organization_edit",
    "organization_detail",
    "organization_delete",
    "partnership_create",
    "partnership_detail",
    "partnership_update",
    "partnership_delete",
    "recommendations_home",
    "recommendations_stats_cards",
    "recommendations_new",
    "recommendations_create",
    "recommendations_autosave",
    "recommendations_manage",
    "recommendations_programs",
    "recommendations_services",
    "recommendations_view",
    "recommendations_edit",
    "recommendations_delete",
    "recommendations_by_area",
    "calendar_event_update",
    # Unified calendar feed (WorkItem hierarchy)
    "work_items_calendar_feed",
    "work_item_modal",
    # WorkItem views (Phase 3)
    "work_item_list",
    "work_item_detail",
    "work_item_create",
    "work_item_edit",
    "work_item_delete",
    "work_item_delete_modal",
    "work_item_tree_partial",
    "work_item_update_progress",
    "work_item_calendar_feed",
    "work_item_sidebar_detail",
    "work_item_sidebar_edit",
    "work_item_sidebar_create",
    "work_item_duplicate",
]
