# Generated by Django 4.2.24 on 2025-09-21 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename provided during upload",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who granted this access, when applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_document_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentaccess",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this access grant is currently active"
            ),
        ),
        migrations.AlterField(
            model_name="documentaccess",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("download", "Download"),
                    ("edit", "Edit"),
                    ("delete", "Delete"),
                    ("share", "Share"),
                    ("upload", "Upload"),
                ],
                help_text="Type of access performed",
                max_length=20,
            ),
        ),
    ]
