# Generated by Django 4.2.24 on 2025-09-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_document_original_filename_documentaccess_granted_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("report", "Assessment Report"),
                    ("correspondence", "Correspondence"),
                    ("profile", "Community Profile"),
                    ("policy", "Policy Document"),
                    ("moa", "Memorandum of Agreement"),
                    ("minutes", "Meeting Minutes"),
                    ("presentation", "Presentation"),
                    ("photo", "Photograph"),
                    ("form", "Form/Template"),
                    ("certificate", "Certificate"),
                    ("legal", "Legal Document"),
                    ("financial", "Financial Document"),
                    ("research", "Research Document"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of document",
                max_length=20,
            ),
        ),
    ]
