# Generated by Django 4.2.24 on 2025-10-01 10:27

import django.core.validators
from django.db import migrations, models
import recommendations.documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload the document file', upload_to=recommendations.documents.models.document_upload_path, validators=[recommendations.documents.models.validate_file_size, recommendations.documents.models.validate_file_mime_type, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'rtf', 'odt', 'ods', 'odp', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'mp3', 'wav', 'ogg', 'zip', 'rar', '7z'])]),
        ),
    ]
