# Generated by Django 5.2.7 on 2025-10-12 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "coordination",
            "0015_organization_barangay_organization_municipality_and_more",
        ),
        ("mana", "0021_add_needvote_model"),
        (
            "monitoring",
            "0023_monitoringentry_monitoring_entry_budget_allocation_within_ceiling_and_more",
        ),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_year",
                    models.IntegerField(
                        help_text="Fiscal year this budget is for (e.g., 2025)",
                        validators=[django.core.validators.MinValueValidator(2024)],
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Budget proposal title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Overview of budget proposal objectives and scope",
                    ),
                ),
                (
                    "total_proposed_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total budget amount proposed (₱)",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current status of budget proposal",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of submission", null=True
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of review", null=True
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Reviewer notes and approval/rejection reasons",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="MOA submitting this budget proposal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_proposals",
                        to="coordination.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this proposal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_budget_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted this proposal",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_budget_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Proposal",
                "verbose_name_plural": "Budget Proposals",
                "ordering": ["-fiscal_year", "organization"],
            },
        ),
        migrations.CreateModel(
            name="ProgramBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budget amount allocated to this program (₱)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Priority level for this program budget",
                        max_length=20,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Justification for budget allocation amount"
                    ),
                ),
                (
                    "expected_outputs",
                    models.TextField(
                        help_text="Expected deliverables and outputs from this program"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_proposal",
                    models.ForeignKey(
                        help_text="Parent budget proposal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_budgets",
                        to="budget_preparation.budgetproposal",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Work plan objective this budget supports",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_allocations",
                        to="planning.workplanobjective",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Budget",
                "verbose_name_plural": "Program Budgets",
                "ordering": ["-priority_level", "-allocated_amount"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personnel", "Personnel Services (PS)"),
                            (
                                "operating",
                                "Maintenance & Other Operating Expenses (MOOE)",
                            ),
                            ("capital", "Capital Outlay (CO)"),
                        ],
                        default="operating",
                        help_text="Appropriation category (PS/MOOE/CO)",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Item description (e.g., 'Office Supplies', 'Training Materials')",
                        max_length=255,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit (₱)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Number of units",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost (auto-calculated: unit_cost × quantity)",
                        max_digits=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or specifications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_budget",
                    models.ForeignKey(
                        help_text="Parent program budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="budget_preparation.programbudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Line Item",
                "verbose_name_plural": "Budget Line Items",
                "ordering": ["category", "-total_cost"],
            },
        ),
        migrations.CreateModel(
            name="BudgetJustification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed rationale for budget allocation",
                    ),
                ),
                (
                    "alignment_with_priorities",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="How this budget aligns with organizational priorities",
                    ),
                ),
                (
                    "expected_impact",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Expected impact and outcomes from this budget allocation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitoring_entry_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="M&E PPA entry supporting this budget allocation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_justifications",
                        to="monitoring.monitoringentry",
                    ),
                ),
                (
                    "needs_assessment_reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Needs assessment supporting this budget request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_justifications",
                        to="mana.assessment",
                    ),
                ),
                (
                    "program_budget",
                    models.ForeignKey(
                        help_text="Program budget being justified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justifications",
                        to="budget_preparation.programbudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Justification",
                "verbose_name_plural": "Budget Justifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="budgetproposal",
            index=models.Index(
                fields=["organization", "fiscal_year"],
                name="budget_prep_organiz_2ee1b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetproposal",
            index=models.Index(fields=["status"], name="budget_prep_status_011cb7_idx"),
        ),
        migrations.AddIndex(
            model_name="budgetproposal",
            index=models.Index(
                fields=["fiscal_year"], name="budget_prep_fiscal__769ca1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetproposal",
            unique_together={("organization", "fiscal_year")},
        ),
        migrations.AddIndex(
            model_name="programbudget",
            index=models.Index(
                fields=["budget_proposal", "priority_level"],
                name="budget_prep_budget__b40eab_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programbudget",
            unique_together={("budget_proposal", "program")},
        ),
        migrations.AddIndex(
            model_name="budgetlineitem",
            index=models.Index(
                fields=["program_budget", "category"],
                name="budget_prep_program_7beec1_idx",
            ),
        ),
    ]
