# Generated by Django 5.2.7 on 2025-10-20 05:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_preparation', '0006_add_expected_outcomes'),
        ('monitoring', '0023_monitoringentry_monitoring_entry_budget_allocation_within_ceiling_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programbudget',
            options={'ordering': ['priority_rank', 'monitoring_entry__title'], 'verbose_name': 'Program Budget', 'verbose_name_plural': 'Program Budgets'},
        ),
        migrations.RemoveIndex(
            model_name='budgetproposal',
            name='budget_prep_fiscal__769ca1_idx',
        ),
        migrations.RemoveIndex(
            model_name='programbudget',
            name='budget_prep_budget__b40eab_idx',
        ),
        migrations.RenameIndex(
            model_name='programbudget',
            new_name='budget_prep_budget__8d8b11_idx',
            old_name='budget_prep_budget__priority_rank_idx',
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Optional sub-category (e.g., salaries, training, equipment)', max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetproposal',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Approval or rejection notes'),
        ),
        migrations.AlterField(
            model_name='budgetproposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the proposal was approved', null=True),
        ),
        migrations.AlterField(
            model_name='budgetproposal',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the proposal was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved for this program (₱)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='justification',
            field=models.TextField(blank=True, help_text='Justification for the requested amount'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='monitoring_entry',
            field=models.ForeignKey(blank=True, help_text='Linked monitoring entry (PPA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_budgets', to='monitoring.monitoringentry'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='priority_rank',
            field=models.PositiveIntegerField(default=1, help_text='Priority ranking within the proposal (1 = highest)'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='program',
            field=models.ForeignKey(blank=True, editable=False, help_text='Legacy field retained for compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_budget_allocations', to='planning.workplanobjective'),
        ),
        migrations.AlterField(
            model_name='programbudget',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount requested for this program (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='programbudget',
            index=models.Index(fields=['monitoring_entry'], name='budget_prep_monitor_5b3eb5_idx'),
        ),
    ]
