from django.urls import path

from . import facilitator_views, participant_views, views

app_name = "mana"

urlpatterns = [
    # Account creation
    path(
        "create-account/",
        facilitator_views.create_account,
        name="create_account",
    ),
    # Assessment selection
    path(
        "participant/assessments/",
        participant_views.participant_assessments_list,
        name="participant_assessments_list",
    ),
    path(
        "facilitator/assessments/",
        facilitator_views.facilitator_assessments_list,
        name="facilitator_assessments_list",
    ),
    # Facilitator dashboard redirects to assessments list
    path(
        "facilitator/dashboard/",
        facilitator_views.facilitator_assessments_list,
        name="facilitator_dashboard_redirect",
    ),
    # Participant-facing routes
    path(
        "assessments/<uuid:assessment_id>/participant/onboarding/",
        participant_views.participant_onboarding,
        name="participant_onboarding",
    ),
    path(
        "assessments/<uuid:assessment_id>/participant/dashboard/",
        participant_views.participant_dashboard,
        name="participant_dashboard",
    ),
    path(
        "assessments/<uuid:assessment_id>/participant/workshops/<str:workshop_type>/",
        participant_views.participant_workshop_detail,
        name="participant_workshop_detail",
    ),
    path(
        "assessments/<uuid:assessment_id>/participant/workshops/<str:workshop_type>/review/",
        participant_views.participant_workshop_review,
        name="participant_workshop_review",
    ),
    path(
        "assessments/<uuid:assessment_id>/participant/workshops/<str:workshop_type>/outputs/",
        participant_views.participant_workshop_outputs,
        name="participant_workshop_outputs",
    ),
    path(
        "assessments/<uuid:assessment_id>/participant/notifications/<int:notification_id>/mark-read/",
        participant_views.mark_notification_read,
        name="mark_notification_read",
    ),
    # Facilitator routes
    path(
        "assessments/<uuid:assessment_id>/facilitator/dashboard/",
        facilitator_views.facilitator_dashboard,
        name="facilitator_dashboard",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/participants/",
        facilitator_views.manage_participants,
        name="facilitator_manage_participants",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/participants/<int:participant_id>/reset/",
        facilitator_views.reset_participant_progress,
        name="facilitator_reset_participant",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/workshops/<str:workshop_type>/advance/",
        facilitator_views.advance_workshop,
        name="facilitator_advance_workshop",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/workshops/<str:workshop_type>/synthesis/",
        facilitator_views.generate_synthesis,
        name="facilitator_generate_synthesis",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/synthesis/<int:synthesis_id>/regenerate/",
        facilitator_views.regenerate_synthesis,
        name="facilitator_regenerate_synthesis",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/synthesis/<int:synthesis_id>/approve/",
        facilitator_views.approve_synthesis,
        name="facilitator_approve_synthesis",
    ),
    path(
        "assessments/<uuid:assessment_id>/facilitator/exports/<str:workshop_type>/<str:format_type>/",
        facilitator_views.export_workshop_responses,
        name="facilitator_export_workshop",
    ),
    # Phase 2: MANA Integration URLs
    path(
        "assessments/<uuid:assessment_id>/tasks/board/",
        views.assessment_tasks_board,
        name="mana_assessment_tasks_board",
    ),
    path(
        "assessments/<uuid:assessment_id>/calendar/",
        views.assessment_calendar,
        name="mana_assessment_calendar",
    ),
    path(
        "assessments/<uuid:assessment_id>/calendar/feed/",
        views.assessment_calendar_feed,
        name="mana_assessment_calendar_feed",
    ),
    path(
        "needs/prioritize/",
        views.needs_prioritization_board,
        name="mana_needs_prioritize",
    ),
    path(
        "needs/update-ranking/",
        views.needs_update_ranking,
        name="mana_needs_update_ranking",
    ),
    path(
        "needs/<int:need_id>/vote/",
        views.need_vote,
        name="mana_need_vote",
    ),
    path(
        "needs/export/",
        views.needs_export,
        name="mana_needs_export",
    ),
]
