# Generated by Django 4.2.21 on 2025-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrecommendation",
            name="category",
            field=models.CharField(
                choices=[
                    ("economic_development", "Economic Development"),
                    ("social_development", "Social Development"),
                    ("cultural_development", "Cultural Development"),
                    ("rehabilitation_development", "Rehabilitation & Development"),
                    ("protection_of_rights", "Protection of Rights"),
                ],
                help_text="Policy category",
                max_length=30,
            ),
        ),
    ]
