# Generated by Django 5.2.7 on 2025-10-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCMAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this OCM access is currently active",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer - Basic Dashboard Access"),
                            ("analyst", "Analyst - Reports & Analytics"),
                            ("executive", "Executive - Full Access"),
                        ],
                        default="viewer",
                        help_text="Level of access granted to the OCM user",
                        max_length=20,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When OCM access was granted"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the user accessed OCM features",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this OCM access grant",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who granted this access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_ocm_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User with OCM access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocm_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OCM Access",
                "verbose_name_plural": "OCM Access Records",
                "db_table": "ocm_access",
                "ordering": ["-granted_at"],
                "permissions": [
                    ("view_ocm_dashboard", "Can view OCM aggregated dashboard"),
                    (
                        "view_consolidated_budget",
                        "Can view consolidated budget across MOAs",
                    ),
                    (
                        "view_planning_overview",
                        "Can view planning overview across MOAs",
                    ),
                    (
                        "view_coordination_matrix",
                        "Can view coordination matrix across MOAs",
                    ),
                    ("generate_ocm_reports", "Can generate OCM reports"),
                    ("export_ocm_data", "Can export OCM data"),
                ],
            },
        ),
    ]
