# Generated by Django 5.2.7 on 2025-10-20 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocmaccess',
            name='access_level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('executive', 'Executive')], default='viewer', help_text='Level of access: viewer (dashboard only), analyst (+ reports), executive (+ exports)', max_length=50, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When OCM access was granted', verbose_name='Granted At'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocm_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted By'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether OCM access is currently active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time user accessed OCM views', null=True, verbose_name='Last Accessed'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this OCM access grant', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='ocmaccess',
            name='user',
            field=models.OneToOneField(help_text='User with OCM access', on_delete=django.db.models.deletion.CASCADE, related_name='ocm_access', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
