# Generated by Django 4.2.21 on 2025-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0006_workshopactivity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopoutput",
            name="output_type",
            field=models.CharField(
                choices=[
                    ("community_map", "Community Map"),
                    ("timeline", "Historical Timeline"),
                    ("asset_inventory", "Asset Inventory"),
                    ("stakeholder_map", "Stakeholder Map"),
                    ("vision_statement", "Vision Statement"),
                    ("needs_assessment", "Needs Assessment"),
                    ("priority_list", "Priority List"),
                    ("organization_map", "Organization Map"),
                    ("collaboration_strategy", "Collaboration Strategy"),
                    ("program_feedback", "Program Feedback"),
                    ("problem_tree", "Problem Tree"),
                    ("solution_inventory", "Solution Inventory"),
                    ("action_plan", "Action Plan"),
                    ("meta_cards", "Meta Cards"),
                    ("flip_charts", "Flip Charts"),
                    ("photos", "Photo Documentation"),
                    ("audio_recording", "Audio Recording"),
                    ("other", "Other Output"),
                ],
                help_text="Type of workshop output",
                max_length=30,
            ),
        ),
    ]
