# Generated by Django 4.2.24 on 2025-09-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0008_add_administrative_relations"),
    ]

    operations = [
        # Drop the old geographic tables from MANA app
        # These models have been moved to the communities app
        migrations.RunSQL(
            "DROP TABLE IF EXISTS mana_spatialdatapoint;",
            reverse_sql="-- Cannot reverse this operation automatically"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS mana_mapvisualization_layers;",
            reverse_sql="-- Cannot reverse this operation automatically"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS mana_mapvisualization;",
            reverse_sql="-- Cannot reverse this operation automatically"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS mana_geographicdatalayer;",
            reverse_sql="-- Cannot reverse this operation automatically"
        ),
    ]
