# Generated by Django 4.2.24 on 2025-09-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0009_remove_geographic_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="GeographicDataLayer"),
                migrations.DeleteModel(name="SpatialDataPoint"),
                migrations.DeleteModel(name="MapVisualization"),
            ],
            database_operations=[],
        ),
    ]
