# Generated by Django 4.2.24 on 2025-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0010_remove_mapvisualization_assessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopactivity",
            name="workshop_outputs",
            field=models.JSONField(
                blank=True,
                help_text="Detailed outputs from the workshop session",
                null=True,
            ),
        ),
    ]
