# Generated by Django 4.2.24 on 2025-09-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_add_multiple_teams_to_stafftask"),
        ("communities", "0024_provincecoverage"),
        ("mana", "0011_workshopactivity_workshop_outputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="province",
            field=models.ForeignKey(
                blank=True,
                help_text="Province being assessed (for regional/provincial assessments)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="common.province",
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="community",
            field=models.ForeignKey(
                blank=True,
                help_text="Community being assessed (for community-level assessments)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="communities.obccommunity",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["province", "status"], name="mana_assess_provinc_0a8eca_idx"
            ),
        ),
    ]
