# Generated by Django 4.2.24 on 2025-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0013_workshopparticipantaccount_workshopsynthesis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopQuestionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_type', models.CharField(choices=[('workshop_1', 'Workshop 1: Understanding the Community Context'), ('workshop_2', 'Workshop 2: Community Aspirations and Priorities'), ('workshop_3', 'Workshop 3: Community Collaboration and Empowerment'), ('workshop_4', 'Workshop 4: Community Feedback on Existing Initiatives'), ('workshop_5', 'Workshop 5: OBCs Needs, Challenges, Factors, and Outcomes'), ('workshop_6', 'Workshop 6: Ways Forward and Action Planning')], help_text='Workshop this question belongs to', max_length=20)),
                ('question_id', models.CharField(help_text='Stable identifier matching schema JSON', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within workshop')),
                ('version', models.CharField(default='v1', help_text='Schema version tag', max_length=20)),
                ('definition', models.JSONField(help_text='Full question payload including text, type, fields, and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workshop Question Definition',
                'verbose_name_plural': 'Workshop Question Definitions',
                'ordering': ['workshop_type', 'order', 'question_id'],
                'unique_together': {('workshop_type', 'question_id', 'version')},
            },
        ),
    ]
