# Generated by Django 4.2.24 on 2025-09-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0015_alter_workshopparticipantaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopparticipantaccount",
            name="facilitator_advanced_to",
            field=models.CharField(
                default="workshop_1",
                help_text="Maximum workshop unlocked by facilitator for this participant",
                max_length=15,
            ),
        ),
    ]
