# Generated by Django 4.2.24 on 2025-09-30 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mana", "0016_add_facilitator_advancement_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitatorAssessmentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        help_text="Assessment the facilitator is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitator_assignments",
                        to="mana.assessment",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Staff/superuser who made this assignment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilitator_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        help_text="Facilitator user assigned to this assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitator_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facilitator Assessment Assignment",
                "verbose_name_plural": "Facilitator Assessment Assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("facilitator", "assessment")},
            },
        ),
    ]
