# Generated by Django 4.2.24 on 2025-09-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0017_add_facilitator_assessment_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("workshop_advanced", "Workshop Advanced"),
                            ("workshop_reminder", "Workshop Reminder"),
                            ("assessment_complete", "Assessment Complete"),
                        ],
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether participant has read this notification",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="Participant receiving this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="mana.workshopparticipantaccount",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related workshop (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="mana.workshopactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Notification",
                "verbose_name_plural": "Workshop Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-created_at"],
                        name="mana_worksh_partici_52f564_idx",
                    ),
                    models.Index(
                        fields=["participant", "is_read"],
                        name="mana_worksh_partici_84dd9e_idx",
                    ),
                ],
            },
        ),
    ]
