# Generated by Django 4.2.24 on 2025-10-01 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0007_event_fiscal_year_event_is_quarterly_coordination_and_more'),
        ('monitoring', '0006_monitoringentrytaskassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mana', '0019_enhance_participant_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='budget_inclusion_date',
            field=models.DateField(blank=True, help_text='Date when this need was included in budget/PPA', null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='community_votes',
            field=models.PositiveIntegerField(default=0, help_text='Votes received during participatory budgeting sessions'),
        ),
        migrations.AddField(
            model_name='need',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, help_text='OOBC staff who forwarded this need', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='need',
            name='forwarded_date',
            field=models.DateField(blank=True, help_text='Date when forwarded to MAO', null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='forwarded_to_mao',
            field=models.ForeignKey(blank=True, help_text='MAO that this need was forwarded to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_needs', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='need',
            name='linked_ppa',
            field=models.ForeignKey(blank=True, help_text='PPA (MonitoringEntry) that addresses this need', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressing_needs', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='need',
            name='submission_date',
            field=models.DateField(blank=True, help_text='Date when community submitted this need', null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='submission_type',
            field=models.CharField(choices=[('assessment_driven', 'Identified During Assessment'), ('community_submitted', 'Community-Submitted')], default='assessment_driven', help_text='How this need was identified', max_length=20),
        ),
        migrations.AddField(
            model_name='need',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, help_text='Community leader who submitted (if community-initiated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_submitted_needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='need',
            name='assessment',
            field=models.ForeignKey(blank=True, help_text='Assessment that identified this need (optional for community-submitted needs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identified_needs', to='mana.assessment'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['submission_type', 'status'], name='mana_need_submiss_b96101_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['submitted_by_user', 'status'], name='mana_need_submitt_7b7195_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['forwarded_to_mao', 'status'], name='mana_need_forward_88cba7_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['linked_ppa'], name='mana_need_linked__734a45_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['community_votes'], name='mana_need_communi_873e72_idx'),
        ),
    ]
