# Generated by Django 4.2.24 on 2025-10-01 05:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0025_add_provincial_submission_tracking'),
        ('mana', '0020_need_budget_inclusion_date_need_community_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_weight', models.PositiveIntegerField(default=1, help_text='Vote weight (1-5 stars). Default is 1 for simple upvote.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment explaining why this need is important')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for fraud detection', null=True)),
                ('need', models.ForeignKey(help_text='The community need being voted for', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mana.need')),
                ('user', models.ForeignKey(help_text='The user who cast this vote', on_delete=django.db.models.deletion.CASCADE, related_name='need_votes', to=settings.AUTH_USER_MODEL)),
                ('voter_community', models.ForeignKey(blank=True, help_text='Community the voter belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_votes', to='communities.obccommunity')),
            ],
            options={
                'verbose_name': 'Need Vote',
                'verbose_name_plural': 'Need Votes',
                'ordering': ['-voted_at'],
                'indexes': [models.Index(fields=['need', '-voted_at'], name='mana_needvo_need_id_2060fd_idx'), models.Index(fields=['user', '-voted_at'], name='mana_needvo_user_id_022ac0_idx'), models.Index(fields=['-voted_at'], name='mana_needvo_voted_a_15b44e_idx')],
                'unique_together': {('need', 'user')},
            },
        ),
    ]
