# Generated manually for BMMS Phase 6 - MANA app migration
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('mana', '0021_add_needvote_model'),
    ]

    operations = [
        # Add nullable organization field to all 31 organization-scoped models
        # NeedsCategory excluded as it's reference data
        
        migrations.AddField(
            model_name='assessment',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_assessments',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='assessmentcategory',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_assessmentcategories',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='assessmentteammember',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_assessmentteammembers',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='baselinedatacollection',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_baselinedatacollections',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='baselineindicator',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_baselineindicators',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='baselinestudy',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_baselinestudies',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='baselinestudyteammember',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_baselinestudyteammembers',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='communityaspirations',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_communityaspirations',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='communitychallenges',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_communitychallenges',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='communitygovernance',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_communitygovernances',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_communityprofiles',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='facilitatorassessmentassignment',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_facilitatorassessmentassignments',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='manareport',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_manareports',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='mappingactivity',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_mappingactivities',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='need',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_needs',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='needsprioritization',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_needsprioritizations',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='needsprioritizationitem',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_needsprioritizationitems',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='needvote',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_needvotes',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_surveys',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_surveyquestions',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_surveyresponses',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopAccesslog',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopaccesslogs',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopactivity',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopactivities',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopnotification',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopnotifications',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopoutput',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopoutputs',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopparticipants',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopparticipantaccount',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopparticipantaccounts',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopquestiondefinition',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopquestiondefinitions',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopresponse',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopresponses',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopsession',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopsessions',
                to='organizations.organization'
            ),
        ),
        migrations.AddField(
            model_name='workshopsynthesis',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mana_workshopsyntheses',
                to='organizations.organization'
            ),
        ),
        
        # Add indexes for performance
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['organization'], name='mana_assess_organiz_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['organization'], name='mana_need_organiz_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organization'], name='mana_survey_organiz_idx'),
        ),
    ]
