# Generated by Django 4.2.24 on 2025-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0005_alter_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mandate',
            field=models.TextField(blank=True, help_text='Official mandate of the organization (particularly for government agencies)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='powers_and_functions',
            field=models.TextField(blank=True, help_text='Powers and functions of the organization (particularly for government agencies)'),
        ),
    ]
