# Generated by Django 4.2.24 on 2025-10-01 04:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordination', '0006_organization_mandate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, help_text='Fiscal year for quarterly coordination meetings', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='event',
            name='is_quarterly_coordination',
            field=models.BooleanField(default=False, help_text='Whether this is an OCM quarterly coordination meeting'),
        ),
        migrations.AddField(
            model_name='event',
            name='pre_meeting_reports_due',
            field=models.DateField(blank=True, help_text='Deadline for MAOs to submit pre-meeting reports', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (January - March)'), ('Q2', 'Q2 (April - June)'), ('Q3', 'Q3 (July - September)'), ('Q4', 'Q4 (October - December)')], help_text='Quarter for quarterly coordination meetings', max_length=2),
        ),
        migrations.CreateModel(
            name='MAOFocalPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary Focal Person'), ('alternate', 'Alternate Focal Person')], default='primary', help_text='Role: primary or alternate focal person', max_length=10)),
                ('designation', models.CharField(help_text='Official title/position within the MAO', max_length=255)),
                ('contact_email', models.EmailField(help_text='Official email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary phone number', max_length=50)),
                ('contact_mobile', models.CharField(blank=True, help_text='Mobile phone number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this focal person is currently active')),
                ('appointed_date', models.DateField(help_text='Date when appointed as focal person')),
                ('end_date', models.DateField(blank=True, help_text='Date when focal person role ended (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this focal person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mao', models.ForeignKey(help_text='MAO that this focal person represents', limit_choices_to={'organization_type': 'bmoa'}, on_delete=django.db.models.deletion.CASCADE, related_name='focal_persons', to='coordination.organization')),
                ('user', models.ForeignKey(help_text='User account for this focal person', on_delete=django.db.models.deletion.CASCADE, related_name='mao_focal_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MAO Focal Person',
                'verbose_name_plural': 'MAO Focal Persons',
                'ordering': ['mao__name', 'role', '-appointed_date'],
                'indexes': [models.Index(fields=['mao', 'is_active'], name='coordinatio_mao_id_c2b615_idx'), models.Index(fields=['user', 'is_active'], name='coordinatio_user_id_f06ede_idx'), models.Index(fields=['role', 'is_active'], name='coordinatio_role_d5cbe0_idx')],
                'unique_together': {('mao', 'user', 'role')},
            },
        ),
    ]
