# Generated by Django 4.2.24 on 2025-10-01 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_monitoringentry_cost_effectiveness_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0012_add_multiple_teams_to_stafftask'),
        ('coordination', '0007_event_fiscal_year_event_is_quarterly_coordination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAOQuarterlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budget_allocated', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget allocated to reported PPAs', max_digits=14, null=True)),
                ('total_obc_beneficiaries', models.PositiveIntegerField(blank=True, help_text='Estimated number of OBC beneficiaries', null=True)),
                ('accomplishments', models.TextField(help_text='Key accomplishments during the quarter')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered')),
                ('plans_next_quarter', models.TextField(blank=True, help_text='Action plans for the next quarter')),
                ('coordination_needs', models.TextField(blank=True, help_text='Support requested from OOBC or other partners')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='stakeholderengagement',
            name='budget_amount_to_allocate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to be allocated during the participatory budgeting session', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stakeholderengagement',
            name='is_participatory_budgeting',
            field=models.BooleanField(default=False, help_text='Whether this engagement facilitates participatory budgeting'),
        ),
        migrations.AddField(
            model_name='stakeholderengagement',
            name='voting_close_date',
            field=models.DateField(blank=True, help_text='When community voting closes for participatory budgeting', null=True),
        ),
        migrations.AddField(
            model_name='stakeholderengagement',
            name='voting_open_date',
            field=models.DateField(blank=True, help_text='When community voting opens for participatory budgeting', null=True),
        ),
        migrations.AddIndex(
            model_name='stakeholderengagement',
            index=models.Index(fields=['is_participatory_budgeting', 'planned_date'], name='coordinatio_is_part_ac77a6_idx'),
        ),
        migrations.AddField(
            model_name='maoquarterlyreport',
            name='mao',
            field=models.ForeignKey(help_text='MAO submitting the quarterly report', limit_choices_to={'organization_type': 'bmoa'}, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reports', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='maoquarterlyreport',
            name='meeting',
            field=models.ForeignKey(help_text='Quarterly coordination meeting where the report was submitted', limit_choices_to={'is_quarterly_coordination': True}, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reports', to='coordination.event'),
        ),
        migrations.AddField(
            model_name='maoquarterlyreport',
            name='ppas_implemented',
            field=models.ManyToManyField(blank=True, help_text='PPAs implemented during the quarter', related_name='mao_quarterly_reports', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='maoquarterlyreport',
            name='regions_covered',
            field=models.ManyToManyField(blank=True, help_text='Regions reached by the reported interventions', related_name='mao_quarterly_reports', to='common.region'),
        ),
        migrations.AddField(
            model_name='maoquarterlyreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_mao_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='maoquarterlyreport',
            index=models.Index(fields=['mao', 'submitted_at'], name='coordinatio_mao_id_b3fe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='maoquarterlyreport',
            index=models.Index(fields=['meeting', 'submitted_at'], name='coordinatio_meeting_63cef5_idx'),
        ),
    ]
