# Generated by Django 4.2.24 on 2025-10-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0009_remove_event_recurrence_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when participant checked in",
                        null=True,
                    ),
                ),
                (
                    "check_in_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("qr_code", "QR Code"),
                            ("nfc", "NFC"),
                        ],
                        default="manual",
                        help_text="Method used for check-in",
                        max_length=20,
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when participant checked out",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this attendance record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="coordination.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="Participant who checked in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="coordination.eventparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "checked_in_at"],
                        name="coordinatio_event_i_8f5d56_idx",
                    )
                ],
                "unique_together": {("event", "participant")},
            },
        ),
    ]
