# Generated by Django 5.2.7 on 2025-10-03 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_stafftask_task_context_and_more"),
        ("communities", "0026_communityevent"),
        ("coordination", "0010_eventattendance"),
        ("mana", "0021_add_needvote_model"),
        ("project_central", "0003_budgetapprovalstage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_project_activity",
            field=models.BooleanField(
                default=False, help_text="Whether this event is a project activity"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="project_activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("project_kickoff", "Project Kickoff"),
                    ("milestone_review", "Milestone Review"),
                    ("stakeholder_consultation", "Stakeholder Consultation"),
                    ("technical_review", "Technical Review"),
                    ("progress_review", "Progress Review"),
                    ("closeout", "Project Closeout"),
                ],
                help_text="Type of project activity (if applicable)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Link event to project workflow (for project activities)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_activities",
                to="project_central.projectworkflow",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["related_project", "start_date"],
                name="coordinatio_related_7513ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_project_activity", "status"],
                name="coordinatio_is_proj_1776a0_idx",
            ),
        ),
    ]
