# Generated by Django 5.2.7 on 2025-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0011_event_is_project_activity_and_more"),
    ]

    operations = [
        # STEP 1: Remove all indexes that reference fields we're about to delete
        # Event model indexes (from migrations 0003 and 0011)
        migrations.RemoveIndex(
            model_name="event",
            name="coordinatio_communi_1b0212_idx",  # Index on ["community", "status"]
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="coordinatio_organiz_127b77_idx",  # Index on ["organizer", "start_date"]
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="coordinatio_related_7513ec_idx",  # Index on ["related_project", "start_date"]
        ),

        # EventParticipant model indexes (from migration 0003)
        migrations.RemoveIndex(
            model_name="eventparticipant",
            name="coordinatio_event_i_5df138_idx",  # Index on ["event", "participant_type"]
        ),
        migrations.RemoveIndex(
            model_name="eventparticipant",
            name="coordinatio_organiz_4bd908_idx",  # Index on ["organization", "event"]
        ),

        # EventAttendance model indexes (from migration 0010)
        migrations.RemoveIndex(
            model_name="eventattendance",
            name="coordinatio_event_i_8f5d56_idx",  # Index on ["event", "checked_in_at"]
        ),

        # EventDocument model indexes (from migration 0003)
        migrations.RemoveIndex(
            model_name="eventdocument",
            name="coordinatio_event_i_56c819_idx",  # Index on ["event", "document_type"]
        ),

        # MAOQuarterlyReport model indexes (from migration 0008)
        migrations.RemoveIndex(
            model_name="maoquarterlyreport",
            name="coordinatio_meeting_63cef5_idx",  # Index on ["meeting", "submitted_at"]
        ),
        migrations.RemoveIndex(
            model_name="maoquarterlyreport",
            name="coordinatio_mao_id_b3fe6a_idx",  # Index on ["mao", "submitted_at"]
        ),

        # STEP 2: Remove unique_together constraints before removing fields
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="eventattendance",
            unique_together=None,
        ),

        # STEP 3: Now safe to remove fields
        migrations.RemoveField(
            model_name="event",
            name="co_organizers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="community",
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="event",
            name="facilitators",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizations",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="event",
            name="parent_event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence_parent",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence_pattern",
        ),
        migrations.RemoveField(
            model_name="event",
            name="related_assessment",
        ),
        migrations.RemoveField(
            model_name="event",
            name="related_engagement",
        ),
        migrations.RemoveField(
            model_name="event",
            name="related_project",
        ),
        migrations.RemoveField(
            model_name="eventdocument",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="event",
        ),
        migrations.RemoveField(
            model_name="maoquarterlyreport",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="eventdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="eventparticipant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="maoquarterlyreport",
            name="mao",
        ),
        migrations.RemoveField(
            model_name="maoquarterlyreport",
            name="ppas_implemented",
        ),
        migrations.RemoveField(
            model_name="maoquarterlyreport",
            name="regions_covered",
        ),
        migrations.RemoveField(
            model_name="maoquarterlyreport",
            name="submitted_by",
        ),
        migrations.DeleteModel(
            name="ActionItem",
        ),
    ]
