# Generated by Django 5.2.7 on 2025-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_add_model_validation_constraints"),
        ("coordination", "0012_add_model_validation_constraints"),
        ("monitoring", "0017_add_model_validation_constraints"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventAttendance",
        ),
        migrations.DeleteModel(
            name="EventDocument",
        ),
        migrations.DeleteModel(
            name="EventParticipant",
        ),
        migrations.DeleteModel(
            name="MAOQuarterlyReport",
        ),
    ]
