# Generated by Django 5.2.7 on 2025-10-11 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_workitem_activity_category_and_more"),
        ("coordination", "0014_coordinationnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="barangay",
            field=models.ForeignKey(
                blank=True,
                help_text="Barangay where the primary office is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="common.barangay",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                help_text="Municipality or city where the primary office is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="common.municipality",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="province",
            field=models.ForeignKey(
                blank=True,
                help_text="Province where the organization's primary office is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="common.province",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Region where the organization's primary office is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="common.region",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["region", "province", "municipality"],
                name="coordinatio_region__402c54_idx",
            ),
        ),
    ]
