# Generated by Django 5.2.7 on 2025-10-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0016_intermoapartnership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intermoapartnership',
            new_name='coordinatio_lead_mo_b3b346_idx',
            old_name='coordination_intermoapartnership_lead_status_idx',
        ),
        migrations.RenameIndex(
            model_name='intermoapartnership',
            new_name='coordinatio_status_ea6f99_idx',
            old_name='coordination_intermoapartnership_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='intermoapartnership',
            new_name='coordinatio_start_d_75720e_idx',
            old_name='coordination_intermoapartnership_dates_idx',
        ),
    ]
