# Generated by Django 4.2.21 on 2025-05-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_stakeholder_stakeholderengagement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communityinfrastructure",
            options={
                "ordering": ["community__barangay__name", "infrastructure_type"],
                "verbose_name": "Community Infrastructure",
                "verbose_name_plural": "Community Infrastructure",
            },
        ),
        migrations.AlterModelOptions(
            name="communitylivelihood",
            options={
                "ordering": [
                    "community__barangay__name",
                    "-is_primary_livelihood",
                    "livelihood_type",
                ],
                "verbose_name": "Community Livelihood",
                "verbose_name_plural": "Community Livelihoods",
            },
        ),
        migrations.AlterModelOptions(
            name="obccommunity",
            options={
                "ordering": [
                    "barangay__municipality__province__region__code",
                    "barangay__municipality__province__name",
                    "barangay__municipality__name",
                    "barangay__name",
                ],
                "verbose_name": "OBC Community",
                "verbose_name_plural": "OBC Communities",
            },
        ),
        migrations.AlterModelOptions(
            name="stakeholder",
            options={
                "ordering": [
                    "community__barangay__name",
                    "stakeholder_type",
                    "full_name",
                ],
                "verbose_name": "Community Stakeholder",
                "verbose_name_plural": "Community Stakeholders",
            },
        ),
        migrations.AlterUniqueTogether(
            name="obccommunity",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="name",
        ),
    ]
