# Generated by Django 4.2.21 on 2025-05-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_remove_community_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obccommunity",
            name="cultural_background",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="other_languages",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="population",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="primary_language",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="priority_needs",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="religious_practices",
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_als",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to Alternative Learning System (ALS)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_clean_water",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to clean water supply",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_communication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to communication (mobile/internet)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_electricity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to electricity",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_formal_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to formal schools",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_government_info",
            field=models.TextField(
                blank=True, help_text="Access to information on government programs"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_healthcare",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to healthcare facilities",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_madrasah",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to Madrasah/Islamic education",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_public_services_challenges",
            field=models.TextField(
                blank=True,
                help_text="Challenges in accessing education, health, infrastructure",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_roads_transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to roads and transportation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="access_sanitation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to sanitation facilities",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="assessment_data_sources",
            field=models.TextField(
                blank=True,
                help_text="Data sources (community consultations, surveys, LGU data)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="brief_historical_background",
            field=models.TextField(
                blank=True,
                help_text="Key historical narratives of the community in the area",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="challenges_impact",
            field=models.TextField(
                blank=True, help_text="Impact of these challenges on the community"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="community_names",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Common name(s) used to refer to the community (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="community_organizations",
            field=models.TextField(
                blank=True,
                help_text="Community organizations/associations (name, focus, contact)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="cultural_miscommunication",
            field=models.TextField(
                blank=True, help_text="Cultural miscommunication challenges"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="cultural_practices_traditions",
            field=models.TextField(
                blank=True, help_text="Notable customs, traditions, festivals"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="cultural_preservation_efforts",
            field=models.TextField(
                blank=True, help_text="Existing cultural preservation efforts"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="cultural_preservation_priorities",
            field=models.TextField(
                blank=True, help_text="Cultural preservation initiative priorities"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="economic_disparities",
            field=models.TextField(
                blank=True, help_text="Poverty, limited employment, economic challenges"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="education_priorities",
            field=models.TextField(
                blank=True,
                help_text="Education priorities (scholarships, skills training, Madrasah support)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="elderly_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of elderly/senior citizens", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="employment_opportunities",
            field=models.TextField(
                blank=True,
                help_text="Description of employment opportunities (formal/informal)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="environmental_degradation",
            field=models.TextField(
                blank=True, help_text="Mining, illegal fishing, environmental issues"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="estimated_obc_population",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of individuals identified as part of the OBC",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="estimated_poverty_incidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_high", "Very High (>70%)"),
                    ("high", "High (50-70%)"),
                    ("moderate", "Moderate (30-50%)"),
                    ("low", "Low (10-30%)"),
                    ("very_low", "Very Low (<10%)"),
                    ("unknown", "Unknown"),
                ],
                help_text="Estimated poverty incidence within OBC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="farmers_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of farmers", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="financial_literacy_access",
            field=models.TextField(
                blank=True,
                help_text="Financial literacy and access to financial services",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="fisherfolk_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of fisherfolk", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="formal_political_representation",
            field=models.TextField(
                blank=True, help_text="Presence in Barangay Council, LGU representation"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="gender_inequality_issues",
            field=models.TextField(
                blank=True, help_text="Gender inequality, early marriage issues"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="governance_policy_challenges",
            field=models.TextField(
                blank=True, help_text="Marginalization, lack of representation issues"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="healthcare_priorities",
            field=models.TextField(
                blank=True, help_text="Healthcare access priorities"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="identified_gaps",
            field=models.TextField(
                blank=True, help_text="Identified gaps based on assessments"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="idps_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Internally Displaced Persons (IDPs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="indigenous_peoples_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Indigenous Peoples (if distinct within OBC)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="informal_leadership_structures",
            field=models.TextField(
                blank=True, help_text="Description of informal leadership structures"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="infrastructure_priorities",
            field=models.TextField(
                blank=True,
                help_text="Infrastructure development priorities (roads, water, health, schools)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="investment_scam_issues",
            field=models.TextField(
                blank=True, help_text="Investment scams and financial fraud issues"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="key_aspirations",
            field=models.TextField(
                blank=True,
                help_text="Key community aspirations (poverty eradication, improved services, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="key_community_leaders",
            field=models.TextField(
                blank=True,
                help_text="Key community leader(s)/focal person(s) with contact details",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="key_findings_last_assessment",
            field=models.TextField(
                blank=True, help_text="Key findings from last needs assessment"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="land_ownership_security_issues",
            field=models.TextField(
                blank=True, help_text="Land ownership and security challenges"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="land_tenure_issues",
            field=models.TextField(
                blank=True,
                help_text="Land tenure issues (lack of titles, disputes, ancestral domain claims)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="languages_spoken",
            field=models.TextField(
                blank=True,
                help_text="Languages spoken in the community (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate for mapping", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="livelihood_program_priorities",
            field=models.TextField(
                blank=True,
                help_text="Livelihood program priorities (agriculture, fisheries, SMEs, Halal, ecotourism)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate for mapping", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="msme_presence",
            field=models.TextField(
                blank=True, help_text="Presence of MSMEs (number and type)"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="obc_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique identifier for the OBC (e.g., R12-SK-PAL-001)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="other_challenges",
            field=models.TextField(
                blank=True,
                help_text="Other specific challenges (ISAL education, Halal industry, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="other_ethnolinguistic_groups",
            field=models.TextField(
                blank=True,
                help_text="Other ethnolinguistic groups present (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="participation_local_governance",
            field=models.TextField(
                blank=True, help_text="Participation in local governance and planning"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="peace_security_priorities",
            field=models.TextField(
                blank=True, help_text="Peace and order/conflict resolution priorities"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="primary_ethnolinguistic_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("magindanaw", "Magindanaw"),
                    ("tausug", "Tausug"),
                    ("maranao", "Maranao"),
                    ("yakan", "Yakan"),
                    ("sama", "Sama"),
                    ("banguingui", "Banguingui"),
                    ("other", "Other"),
                ],
                help_text="Primary ethnolinguistic group",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="primary_livelihoods",
            field=models.TextField(
                blank=True,
                help_text="Primary livelihoods (e.g., Rice Farming, Coconut Production, Fishing)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="proximity_to_barmm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adjacent", "Adjacent to BARMM"),
                    ("near", "Near BARMM"),
                    ("distant", "Distant from BARMM"),
                ],
                help_text="Proximity to BARMM boundaries",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="purok_sitio",
            field=models.CharField(
                blank=True,
                help_text="Specific Purok/Sitio within the barangay",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="pwd_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Persons with Disabilities (PWDs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="relationship_with_lgu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaborative", "Collaborative"),
                    ("strained", "Strained"),
                    ("minimal", "Minimal"),
                    ("good", "Good"),
                    ("excellent", "Excellent"),
                ],
                help_text="Relationship with LGU",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="relevant_lgu_officials",
            field=models.TextField(
                blank=True,
                help_text="Relevant LGU official(s) and their contact information",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="religious_affiliation",
            field=models.TextField(
                blank=True, help_text="Religious affiliation and specific practices"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="secondary_livelihoods",
            field=models.TextField(
                blank=True, help_text="Secondary livelihoods in the community"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="social_instability_conflict",
            field=models.TextField(
                blank=True, help_text="Rido, security issues, social conflicts"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="solo_parents_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of solo parents", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="specific_project_proposals",
            field=models.TextField(
                blank=True,
                help_text="Specific project proposals/ideas from the community",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="substance_abuse_issues",
            field=models.TextField(
                blank=True, help_text="Drug use, substance abuse issues"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="total_barangay_population",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total barangay population for context", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="traditional_leaders_role",
            field=models.TextField(
                blank=True,
                help_text="Role of traditional leaders (Imams, Elders, Chieftains)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="women_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of women in the community", null=True
            ),
        ),
        migrations.AlterField(
            model_name="obccommunity",
            name="community_leader",
            field=models.CharField(
                blank=True,
                help_text="Name of the primary community leader",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="obccommunity",
            name="specific_location",
            field=models.CharField(
                blank=True,
                help_text="Additional specific location details",
                max_length=255,
            ),
        ),
    ]
