# Generated by Django 4.2.21 on 2025-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0004_remove_obccommunity_cultural_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="obccommunity",
            name="religious_csos_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of religious CSOs in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="source_document_reference",
            field=models.TextField(
                blank=True,
                help_text="Document source and page number (e.g., 'OBC MANA Region 12, p.7')",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="teachers_asatidz_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Teachers/Asatidz (Islamic teachers)",
                null=True,
            ),
        ),
    ]
