# Generated by Django 4.2.21 on 2025-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_obccommunity_religious_csos_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obccommunity",
            name="employment_opportunities",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="msme_presence",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="religious_csos_count",
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="associations_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Associations in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="csos_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Civil Society Organizations (CSOs) in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_cooperatives",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Cooperatives in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_employed_obc",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of Employed OBC Individuals", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_micro_enterprises",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Micro-Enterprises (such as Sari-Sari Stores, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_social_enterprises",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Social Enterprises in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_unbanked_obc",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of OBC Individuals without Access to Financial Services (Unbanked)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="religious_leaders_ulama_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Religious Leaders (Ulama) in the community",
                null=True,
            ),
        ),
    ]
