# Generated by Django 4.2.24 on 2025-09-20 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_region_province_municipality_barangay"),
        ("communities", "0006_remove_obccommunity_employment_opportunities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MunicipalityCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_obc_communities",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of identified Bangsamoro communities in the municipality",
                        null=True,
                    ),
                ),
                (
                    "estimated_obc_population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated Bangsamoro population across the municipality",
                        null=True,
                    ),
                ),
                (
                    "key_barangays",
                    models.TextField(
                        blank=True,
                        help_text="Barangays or sitios with notable Bangsamoro presence (comma-separated)",
                    ),
                ),
                (
                    "existing_support_programs",
                    models.TextField(
                        blank=True,
                        help_text="Active government or partner support programs",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or coordination notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded this municipality",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municipality_coverages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipality",
                    models.OneToOneField(
                        help_text="LGU where Bangsamoro communities are present",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obc_coverage",
                        to="common.municipality",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="municipality_coverages_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bangsamoro Municipality Coverage",
                "verbose_name_plural": "Bangsamoro Municipality Coverages",
                "ordering": [
                    "municipality__province__region__name",
                    "municipality__province__name",
                    "municipality__name",
                ],
            },
        ),
    ]
