# Generated by Django 4.2.24 on 2025-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0007_municipalitycoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitycoverage",
            name="auto_sync",
            field=models.BooleanField(
                default=True,
                help_text="Keep totals in sync with registered barangay communities",
            ),
        ),
    ]
