# Generated by Django 4.2.24 on 2025-09-20 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0008_municipalitycoverage_auto_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_als",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to Alternative Learning System (ALS)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_clean_water",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to clean water supply",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_communication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to communication (mobile/internet)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_electricity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to electricity",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_formal_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to formal schools",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_government_info",
            field=models.TextField(
                blank=True, help_text="Access to information on government programs"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_healthcare",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to healthcare facilities",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_madrasah",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to Madrasah/Islamic education",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_public_services_challenges",
            field=models.TextField(
                blank=True,
                help_text="Challenges in accessing education, health, infrastructure",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_roads_transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to roads and transportation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="access_sanitation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("none", "None"),
                ],
                help_text="Access to sanitation facilities",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="adults_31_59",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of adults aged 31-59", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="assessment_data_sources",
            field=models.TextField(
                blank=True,
                help_text="Data sources (community consultations, surveys, LGU data)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="associations_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Associations in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="brief_historical_background",
            field=models.TextField(
                blank=True,
                help_text="Key historical narratives of the community in the area",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="challenges_impact",
            field=models.TextField(
                blank=True, help_text="Impact of these challenges on the community"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="children_0_12",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of children aged 0-12", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="community_leader",
            field=models.CharField(
                blank=True,
                help_text="Name of the primary community leader",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="community_names",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Common name(s) used to refer to the community (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="community_organizations",
            field=models.TextField(
                blank=True,
                help_text="Community organizations/associations (name, focus, contact)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="csos_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Civil Society Organizations (CSOs) in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="cultural_miscommunication",
            field=models.TextField(
                blank=True, help_text="Cultural miscommunication challenges"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="cultural_practices_traditions",
            field=models.TextField(
                blank=True, help_text="Notable customs, traditions, festivals"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="cultural_preservation_efforts",
            field=models.TextField(
                blank=True, help_text="Existing cultural preservation efforts"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="cultural_preservation_priorities",
            field=models.TextField(
                blank=True, help_text="Cultural preservation initiative priorities"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="development_status",
            field=models.CharField(
                choices=[
                    ("developing", "Developing"),
                    ("established", "Established"),
                    ("vulnerable", "Vulnerable"),
                    ("thriving", "Thriving"),
                    ("at_risk", "At Risk"),
                ],
                default="developing",
                help_text="Current development status of the community",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="economic_disparities",
            field=models.TextField(
                blank=True, help_text="Poverty, limited employment, economic challenges"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="education_priorities",
            field=models.TextField(
                blank=True,
                help_text="Education priorities (scholarships, skills training, Madrasah support)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="elderly_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of elderly/senior citizens", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="environmental_degradation",
            field=models.TextField(
                blank=True, help_text="Mining, illegal fishing, environmental issues"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="established_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year the community was established",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2030),
                ],
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="estimated_poverty_incidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_high", "Very High (>70%)"),
                    ("high", "High (50-70%)"),
                    ("moderate", "Moderate (30-50%)"),
                    ("low", "Low (10-30%)"),
                    ("very_low", "Very Low (<10%)"),
                    ("unknown", "Unknown"),
                ],
                help_text="Estimated poverty incidence within OBC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="families",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of families in the community", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="farmers_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of farmers", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="financial_literacy_access",
            field=models.TextField(
                blank=True,
                help_text="Financial literacy and access to financial services",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="fisherfolk_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of fisherfolk", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="formal_political_representation",
            field=models.TextField(
                blank=True, help_text="Presence in Barangay Council, LGU representation"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="gender_inequality_issues",
            field=models.TextField(
                blank=True, help_text="Gender inequality, early marriage issues"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="governance_policy_challenges",
            field=models.TextField(
                blank=True, help_text="Marginalization, lack of representation issues"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="has_madrasah",
            field=models.BooleanField(
                default=False,
                help_text="Whether the community has a madrasah/Islamic school",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="has_mosque",
            field=models.BooleanField(
                default=False, help_text="Whether the community has a mosque"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="healthcare_priorities",
            field=models.TextField(
                blank=True, help_text="Healthcare access priorities"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="households",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of households in the community", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="identified_gaps",
            field=models.TextField(
                blank=True, help_text="Identified gaps based on assessments"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="idps_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Internally Displaced Persons (IDPs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="indigenous_peoples_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Indigenous Peoples (if distinct within OBC)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="informal_leadership_structures",
            field=models.TextField(
                blank=True, help_text="Description of informal leadership structures"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="infrastructure_priorities",
            field=models.TextField(
                blank=True,
                help_text="Infrastructure development priorities (roads, water, health, schools)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="investment_scam_issues",
            field=models.TextField(
                blank=True, help_text="Investment scams and financial fraud issues"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this community record is active"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="key_aspirations",
            field=models.TextField(
                blank=True,
                help_text="Key community aspirations (poverty eradication, improved services, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="key_community_leaders",
            field=models.TextField(
                blank=True,
                help_text="Key community leader(s)/focal person(s) with contact details",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="key_findings_last_assessment",
            field=models.TextField(
                blank=True, help_text="Key findings from last needs assessment"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="land_ownership_security_issues",
            field=models.TextField(
                blank=True, help_text="Land ownership and security challenges"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="land_tenure_issues",
            field=models.TextField(
                blank=True,
                help_text="Land tenure issues (lack of titles, disputes, ancestral domain claims)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="languages_spoken",
            field=models.TextField(
                blank=True,
                help_text="Languages spoken in the community (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate for mapping", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="leader_contact",
            field=models.CharField(
                blank=True,
                help_text="Contact information for community leader",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="livelihood_program_priorities",
            field=models.TextField(
                blank=True,
                help_text="Livelihood program priorities (agriculture, fisheries, SMEs, Halal, ecotourism)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate for mapping", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="migration_history",
            field=models.TextField(
                blank=True, help_text="Migration history and patterns"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="needs_assessment_date",
            field=models.DateField(
                blank=True, help_text="Date of last needs assessment", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_cooperatives",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Cooperatives in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_employed_obc",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of Employed OBC Individuals", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_micro_enterprises",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Micro-Enterprises (such as Sari-Sari Stores, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_social_enterprises",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Social Enterprises in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_unbanked_obc",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of OBC Individuals without Access to Financial Services (Unbanked)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="obc_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique identifier for the OBC (e.g., R12-SK-PAL-001)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="origin_story",
            field=models.TextField(
                blank=True, help_text="Story of how the community was established"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="other_challenges",
            field=models.TextField(
                blank=True,
                help_text="Other specific challenges (ISAL education, Halal industry, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="other_ethnolinguistic_groups",
            field=models.TextField(
                blank=True,
                help_text="Other ethnolinguistic groups present (comma-separated)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="participation_local_governance",
            field=models.TextField(
                blank=True, help_text="Participation in local governance and planning"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="peace_security_priorities",
            field=models.TextField(
                blank=True, help_text="Peace and order/conflict resolution priorities"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="primary_ethnolinguistic_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("magindanaw", "Magindanaw"),
                    ("tausug", "Tausug"),
                    ("maranao", "Maranao"),
                    ("yakan", "Yakan"),
                    ("sama", "Sama"),
                    ("banguingui", "Banguingui"),
                    ("other", "Other"),
                ],
                help_text="Primary ethnolinguistic group",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="primary_livelihoods",
            field=models.TextField(
                blank=True,
                help_text="Primary livelihoods (e.g., Rice Farming, Coconut Production, Fishing)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="proximity_to_barmm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adjacent", "Adjacent to BARMM"),
                    ("near", "Near BARMM"),
                    ("distant", "Distant from BARMM"),
                ],
                help_text="Proximity to BARMM boundaries",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="purok_sitio",
            field=models.CharField(
                blank=True,
                help_text="Specific Purok/Sitio within the barangay",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="pwd_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Persons with Disabilities (PWDs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="relationship_with_lgu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaborative", "Collaborative"),
                    ("strained", "Strained"),
                    ("minimal", "Minimal"),
                    ("good", "Good"),
                    ("excellent", "Excellent"),
                ],
                help_text="Relationship with LGU",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="relevant_lgu_officials",
            field=models.TextField(
                blank=True,
                help_text="Relevant LGU official(s) and their contact information",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="religious_affiliation",
            field=models.TextField(
                blank=True, help_text="Religious affiliation and specific practices"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="religious_leaders_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of religious leaders (Imam, Ustadz, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="religious_leaders_ulama_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Religious Leaders (Ulama) in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="secondary_livelihoods",
            field=models.TextField(
                blank=True, help_text="Secondary livelihoods in the community"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="seniors_60_plus",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of seniors aged 60 and above", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="settlement_type",
            field=models.CharField(
                choices=[
                    ("village", "Village"),
                    ("subdivision", "Subdivision"),
                    ("sitio", "Sitio"),
                    ("purok", "Purok"),
                    ("compound", "Compound"),
                    ("dispersed", "Dispersed Settlement"),
                ],
                default="village",
                help_text="Type of settlement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="social_instability_conflict",
            field=models.TextField(
                blank=True, help_text="Rido, security issues, social conflicts"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="solo_parents_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of solo parents", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="source_document_reference",
            field=models.TextField(
                blank=True,
                help_text="Document source and page number (e.g., 'OBC MANA Region 12, p.7')",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="specific_location",
            field=models.CharField(
                blank=True,
                help_text="Additional specific location details",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="specific_project_proposals",
            field=models.TextField(
                blank=True,
                help_text="Specific project proposals/ideas from the community",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="substance_abuse_issues",
            field=models.TextField(
                blank=True, help_text="Drug use, substance abuse issues"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="teachers_asatidz_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Teachers/Asatidz (Islamic teachers)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="total_barangay_population",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total barangay population for context", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="traditional_leaders_role",
            field=models.TextField(
                blank=True,
                help_text="Role of traditional leaders (Imams, Elders, Chieftains)",
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="women_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of women in the community", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="youth_13_30",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of youth aged 13-30", null=True
            ),
        ),
        migrations.AlterField(
            model_name="municipalitycoverage",
            name="estimated_obc_population",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of individuals identified as part of the OBC",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="municipalitycoverage",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the community"
            ),
        ),
    ]
