# Generated by Django 4.2.24 on 2025-09-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0009_municipalitycoverage_access_als_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipalitycoverage",
            options={
                "ordering": [
                    "municipality__province__region__name",
                    "municipality__province__name",
                    "municipality__name",
                ],
                "verbose_name": "Bangsamoro Municipality OBC",
                "verbose_name_plural": "Bangsamoro Municipality OBCs",
            },
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="cultural_background",
            field=models.TextField(
                blank=True,
                help_text="Cultural background and traditions (legacy field retained for compatibility)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Primary community name (legacy field retained for compatibility)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="other_languages",
            field=models.CharField(
                blank=True,
                help_text="Other languages spoken (comma-separated, legacy field retained for compatibility)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="population",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total population of the community (legacy field retained for compatibility)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="primary_language",
            field=models.CharField(
                blank=True,
                help_text="Primary language spoken in the community (legacy field retained for compatibility)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="priority_needs",
            field=models.TextField(
                blank=True,
                help_text="Priority needs identified for the community (legacy field retained for compatibility)",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="religious_practices",
            field=models.TextField(
                blank=True,
                help_text="Religious practices and observances (legacy field retained for compatibility)",
            ),
        ),
    ]
