# Generated by Django 4.2.24 on 2025-09-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0011_remove_municipalitycoverage_has_madrasah_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="children_0_12",
        ),
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="youth_13_30",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="children_0_12",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="youth_13_30",
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="adolescents_10_14",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of adolescents aged 10-14", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="children_0_9",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of children aged 0-9", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="youth_15_30",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of youth aged 15-30", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="adolescents_10_14",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of adolescents aged 10-14", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="children_0_9",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of children aged 0-9", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="youth_15_30",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of youth aged 15-30", null=True
            ),
        ),
    ]
