# Generated by Django 4.2.24 on 2025-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0012_remove_municipalitycoverage_children_0_12_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipalitycoverage",
            name="primary_ethnolinguistic_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("badjao", "Badjao"),
                    ("iranun", "Iranun"),
                    ("jama_mapun", "Jama Mapun"),
                    ("kagan_kalagan", "Kagan/Kalagan"),
                    ("kolibugan", "Kolibugan"),
                    ("maguindanaon", "Maguindanaon"),
                    ("meranaw", "Meranaw"),
                    ("molbog", "Molbog"),
                    ("palawani", "Palawani"),
                    ("sama", "Sama"),
                    ("sangil", "Sangil"),
                    ("tausug", "Tausug"),
                    ("yakan", "Yakan"),
                    ("other", "Other"),
                ],
                help_text="Primary ethnolinguistic group",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="obccommunity",
            name="primary_ethnolinguistic_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("badjao", "Badjao"),
                    ("iranun", "Iranun"),
                    ("jama_mapun", "Jama Mapun"),
                    ("kagan_kalagan", "Kagan/Kalagan"),
                    ("kolibugan", "Kolibugan"),
                    ("maguindanaon", "Maguindanaon"),
                    ("meranaw", "Meranaw"),
                    ("molbog", "Molbog"),
                    ("palawani", "Palawani"),
                    ("sama", "Sama"),
                    ("sangil", "Sangil"),
                    ("tausug", "Tausug"),
                    ("yakan", "Yakan"),
                    ("other", "Other"),
                ],
                help_text="Primary ethnolinguistic group",
                max_length=50,
            ),
        ),
    ]
