# Generated by Django 4.2.24 on 2025-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "communities",
            "0013_alter_municipalitycoverage_primary_ethnolinguistic_group_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="elderly_count",
        ),
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="religious_leaders_ulama_count",
        ),
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="teachers_asatidz_count",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="elderly_count",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="religious_leaders_ulama_count",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="teachers_asatidz_count",
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="migrants_transients_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of migrants/transients", null=True
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="other_vulnerable_sectors",
            field=models.TextField(
                blank=True, help_text="Other vulnerable sectors not listed above"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="unemployed_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of unemployed individuals", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="migrants_transients_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of migrants/transients", null=True
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="other_vulnerable_sectors",
            field=models.TextField(
                blank=True, help_text="Other vulnerable sectors not listed above"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="unemployed_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of unemployed individuals", null=True
            ),
        ),
    ]
