# Generated by Django 4.2.24 on 2025-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0014_remove_municipalitycoverage_elderly_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitycoverage",
            name="asatidz_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of Asatidz (Islamic teachers/instructors)"
            ),
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="other_cultural_facilities",
            field=models.TextField(
                blank=True,
                help_text="Other cultural facilities or assets not listed above",
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="asatidz_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of Asatidz (Islamic teachers/instructors)"
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="other_cultural_facilities",
            field=models.TextField(
                blank=True,
                help_text="Other cultural facilities or assets not listed above",
            ),
        ),
    ]
