# Generated by Django 4.2.24 on 2025-09-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0016_obccommunity_unique_obccommunity_per_barangay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="municipalitycoverage",
            name="number_of_cooperatives",
        ),
        migrations.RemoveField(
            model_name="obccommunity",
            name="number_of_cooperatives",
        ),
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_peoples_organizations",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of People's Organizations in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_peoples_organizations",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of People's Organizations in the community",
                null=True,
            ),
        ),
    ]
