# Generated by Django 4.2.24 on 2025-09-22 16:50

from django.db import migrations, models


def map_development_to_unemployment(apps, schema_editor):
    """Translate legacy development status values into unemployment rates."""

    status_map = {
        "thriving": "very_low",
        "established": "low",
        "developing": "moderate",
        "vulnerable": "high",
        "at_risk": "extremely_high",
    }

    OBCCommunity = apps.get_model("communities", "OBCCommunity")
    MunicipalityCoverage = apps.get_model("communities", "MunicipalityCoverage")

    for community in OBCCommunity.objects.all():
        rate = status_map.get(community.development_status, "unknown")
        community.unemployment_rate = rate
        community.save(update_fields=["unemployment_rate"])

    for coverage in MunicipalityCoverage.objects.all():
        rate = status_map.get(coverage.development_status, "unknown")
        coverage.unemployment_rate = rate
        coverage.save(update_fields=["unemployment_rate"])


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_rename_cooperatives_to_peoples_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitycoverage',
            name='financial_access_level',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('none', 'None')], help_text='Access to banking and financial services', max_length=20),
        ),
        migrations.AddField(
            model_name='municipalitycoverage',
            name='unemployment_rate',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('very_low', 'Very Low (<10%)'), ('low', 'Low (10-20%)'), ('moderate', 'Moderate (20-30%)'), ('high', 'High (30-40%)'), ('very_high', 'Very High (40-50%)'), ('extremely_high', 'Extremely High (>50%)')], default='unknown', help_text='Estimated unemployment rate within the community', max_length=20),
        ),
        migrations.AddField(
            model_name='obccommunity',
            name='financial_access_level',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('none', 'None')], help_text='Access to banking and financial services', max_length=20),
        ),
        migrations.AddField(
            model_name='obccommunity',
            name='unemployment_rate',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('very_low', 'Very Low (<10%)'), ('low', 'Low (10-20%)'), ('moderate', 'Moderate (20-30%)'), ('high', 'High (30-40%)'), ('very_high', 'Very High (40-50%)'), ('extremely_high', 'Extremely High (>50%)')], default='unknown', help_text='Estimated unemployment rate within the community', max_length=20),
        ),
        migrations.RunPython(map_development_to_unemployment, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='municipalitycoverage',
            name='development_status',
        ),
        migrations.RemoveField(
            model_name='municipalitycoverage',
            name='financial_literacy_access',
        ),
        migrations.RemoveField(
            model_name='municipalitycoverage',
            name='number_of_employed_obc',
        ),
        migrations.RemoveField(
            model_name='obccommunity',
            name='development_status',
        ),
        migrations.RemoveField(
            model_name='obccommunity',
            name='financial_literacy_access',
        ),
        migrations.RemoveField(
            model_name='obccommunity',
            name='number_of_employed_obc',
        ),
        migrations.AlterField(
            model_name='municipalitycoverage',
            name='estimated_poverty_incidence',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('very_low', 'Very Low (<10%)'), ('low', 'Low (10-20%)'), ('moderate', 'Moderate (20-30%)'), ('high', 'High (30-40%)'), ('very_high', 'Very High (40-50%)'), ('extremely_high', 'Extremely High (>50%)')], help_text='Estimated poverty incidence within OBC', max_length=20),
        ),
        migrations.AlterField(
            model_name='obccommunity',
            name='estimated_poverty_incidence',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('very_low', 'Very Low (<10%)'), ('low', 'Low (10-20%)'), ('moderate', 'Moderate (20-30%)'), ('high', 'High (30-40%)'), ('very_high', 'Very High (40-50%)'), ('extremely_high', 'Extremely High (>50%)')], help_text='Estimated poverty incidence within OBC', max_length=20),
        ),
    ]
