# Generated by Django 4.2.24 on 2025-09-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0018_remove_municipalitycoverage_development_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitycoverage",
            name="number_of_cooperatives",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Cooperatives in the community",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="obccommunity",
            name="number_of_cooperatives",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Cooperatives in the community",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="municipalitycoverage",
            name="unemployment_rate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select..."),
                    ("unknown", "Unknown"),
                    ("very_low", "Very Low (<10%)"),
                    ("low", "Low (10-20%)"),
                    ("moderate", "Moderate (20-30%)"),
                    ("high", "High (30-40%)"),
                    ("very_high", "Very High (40-50%)"),
                    ("extremely_high", "Extremely High (>50%)"),
                ],
                help_text="Estimated unemployment rate within the community",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="obccommunity",
            name="unemployment_rate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select..."),
                    ("unknown", "Unknown"),
                    ("very_low", "Very Low (<10%)"),
                    ("low", "Low (10-20%)"),
                    ("moderate", "Moderate (20-30%)"),
                    ("high", "High (30-40%)"),
                    ("very_high", "Very High (40-50%)"),
                    ("extremely_high", "Extremely High (>50%)"),
                ],
                help_text="Estimated unemployment rate within the community",
                max_length=20,
            ),
        ),
    ]
