# Generated by Django 4.2.24 on 2025-09-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0019_add_cooperatives_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipalitycoverage",
            name="other_cultural_facilities",
            field=models.TextField(
                blank=True,
                help_text="Other cultural facilities, artefacts, or assets not listed above",
            ),
        ),
        migrations.AlterField(
            model_name="obccommunity",
            name="other_cultural_facilities",
            field=models.TextField(
                blank=True,
                help_text="Other cultural facilities, artefacts, or assets not listed above",
            ),
        ),
    ]
