# Generated by Django 4.2.16 on 2025-09-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0022_add_soft_delete_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spatialdatapoint',
            new_name='communities_communi_896657_idx',
            old_name='communities_spatia_communi_8a49cd_idx',
        ),
        migrations.RenameIndex(
            model_name='spatialdatapoint',
            new_name='communities_latitud_2fa309_idx',
            old_name='communities_spatia_latitud_c64138_idx',
        ),
        migrations.RenameIndex(
            model_name='spatialdatapoint',
            new_name='communities_data_la_5ef31d_idx',
            old_name='communities_spatia_data_la_ecf7b1_idx',
        ),
        migrations.AlterField(
            model_name='mapvisualization',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Community this visualization focuses on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_map_visualizations', to='communities.obccommunity'),
        ),
        migrations.AlterField(
            model_name='municipalitycoverage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record for deletion review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obccommunity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record for deletion review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
