# Generated by Django 4.2.24 on 2025-09-30 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communities", "0024_provincecoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="provincecoverage",
            name="is_submitted",
            field=models.BooleanField(
                default=False,
                help_text="Whether this record has been submitted by a MANA participant (becomes read-only)",
            ),
        ),
        migrations.AddField(
            model_name="provincecoverage",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this record was submitted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provincecoverage",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="province_coverages_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
