# Generated by Django 4.2.24 on 2025-10-01 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_calendarresource_recurringeventpattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0025_add_provincial_submission_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('cultural', 'Cultural Celebration'), ('religious', 'Religious Observance'), ('meeting', 'Community Meeting'), ('training', 'Community Training'), ('disaster', 'Disaster/Emergency'), ('other', 'Other')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public calendar')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring event')),
                ('is_recurrence_exception', models.BooleanField(default=False, help_text='True if this instance was edited separately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_events', to='communities.obccommunity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_community_events', to=settings.AUTH_USER_MODEL)),
                ('recurrence_parent', models.ForeignKey(blank=True, help_text='Parent event if this is a recurrence instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_instances', to='communities.communityevent')),
                ('recurrence_pattern', models.ForeignKey(blank=True, help_text='Recurrence pattern configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_community_events', to='common.recurringeventpattern')),
            ],
            options={
                'verbose_name': 'Community Event',
                'verbose_name_plural': 'Community Events',
                'db_table': 'communities_community_event',
                'ordering': ['-start_date'],
            },
        ),
    ]
