# Generated by Django 5.2.7 on 2025-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0030_make_organization_required'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='municipalitycoverage',
            name='communities_munici_org_idx',
        ),
        migrations.RemoveIndex(
            model_name='obccommunity',
            name='communities_obccom_org_idx',
        ),
        migrations.RemoveIndex(
            model_name='stakeholder',
            name='communities_stakeh_org_idx',
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='communityinfrastructure',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='communitylivelihood',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='geographicdatalayer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='mapvisualization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='municipalitycoverage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='obccommunity',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='provincecoverage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='spatialdatapoint',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stakeholderengagement',
            name='organization',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization or institution they represent', max_length=255),
        ),
    ]
