# Generated by Django 5.2.7 on 2025-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_tracking', '0003_policyimplementationmilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecommendation',
            name='category',
            field=models.CharField(choices=[('economic_development', 'Economic Development'), ('social_development', 'Social Development'), ('cultural_development', 'Cultural Development'), ('promotion_of_welfare', 'Promotion of Welfare'), ('rehabilitation_development', 'Rehabilitation & Development'), ('protection_of_rights', 'Protection of Rights')], help_text='Policy category', max_length=30),
        ),
    ]
