# Generated by Django 5.2.7 on 2025-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_tracking', '0004_add_promotion_of_welfare_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecommendation',
            name='community_validated',
            field=models.BooleanField(default=False, help_text='Whether this recommendation has been validated by the community'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='consultation_dates',
            field=models.JSONField(blank=True, help_text='Array of consultation date objects with location and participant counts', null=True),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='consultation_references',
            field=models.TextField(blank=True, help_text='References to consultations held (dates, locations, participants)'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='core_recommendation_other',
            field=models.CharField(blank=True, help_text="Specify if 'Other' is selected in core recommendation type", max_length=255),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='core_recommendation_type',
            field=models.CharField(blank=True, choices=[('scholarships', 'Scholarships & Financial Assistance for Higher Education'), ('madaris_support', 'Support to OBC Madaris'), ('halal_enterprise', 'Support to OBC Halal Enterprise Development'), ('social_services', 'Expansion of Social Services (TABANG, AMBAG, KAPYANAN)'), ('cultural_development', 'Cultural Development Program'), ('women_youth', 'Women and Youth Development Program'), ('tourism', 'Tourism Development Program'), ('infrastructure', 'Infrastructure Development'), ('governance_participation', 'Increased Participation in Governance and Planning'), ('institutional_partnerships', 'Institutional Partnerships and Coordination'), ('other', 'Other (Please specify)')], help_text='Select from 10 core OBC recommendation types', max_length=30),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='cso_partners',
            field=models.TextField(blank=True, help_text='Civil Society Organizations and other partners'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='cultural_alignment',
            field=models.TextField(blank=True, help_text='How this aligns with Bangsamoro cultural values'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='equity_considerations',
            field=models.TextField(blank=True, help_text='How this addresses equity and inclusion'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='identified_risks',
            field=models.JSONField(blank=True, help_text='Array of risk objects with severity, mitigation, and contingency plans', null=True),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='importance',
            field=models.CharField(choices=[('high', 'High Importance'), ('low', 'Low Importance')], default='high', help_text='Importance level (High/Low)', max_length=10),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='lgus_involved',
            field=models.TextField(blank=True, help_text='Local Government Units involved in implementation'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='long_term_benefits',
            field=models.TextField(blank=True, help_text='Long-term benefits (3+ years)'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='ngas_involved',
            field=models.TextField(blank=True, help_text='National Government Agencies involved'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='performance_indicators',
            field=models.JSONField(blank=True, help_text='Array of performance indicator objects with baselines and targets', null=True),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('policy', 'Policy Recommendation'), ('program', 'Systematic Program'), ('service', 'Service Improvement')], default='policy', help_text='Type of recommendation: Policy, Program, or Service', max_length=10),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='reporting_schedule',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], help_text='Reporting frequency for M&E', max_length=20),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='research_data',
            field=models.TextField(blank=True, help_text='Research data, official statistics, and citations'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='short_term_benefits',
            field=models.TextField(blank=True, help_text='Short-term benefits (1-2 years)'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='stakeholder_feedback_detailed',
            field=models.TextField(blank=True, help_text='Detailed stakeholder feedback from consultations'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='sustainability_measures',
            field=models.TextField(blank=True, help_text='Measures to ensure long-term sustainability'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='tracking_mechanisms',
            field=models.TextField(blank=True, help_text='How progress will be monitored and tracked'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='urgency',
            field=models.CharField(choices=[('high', 'High Urgency'), ('low', 'Low Urgency')], default='high', help_text='Urgency level (High/Low)', max_length=10),
        ),
    ]
