# Generated by Django 5.2.7 on 2025-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_tracking', '0005_add_comprehensive_recommendation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecommendation',
            name='secondary_categories',
            field=models.JSONField(blank=True, help_text='Additional categories if Comprehensive is selected', null=True),
        ),
        migrations.AlterField(
            model_name='policyrecommendation',
            name='category',
            field=models.CharField(choices=[('economic_development', 'Economic Development'), ('social_development', 'Social Development'), ('cultural_development', 'Cultural Development'), ('promotion_of_welfare', 'Promotion of Welfare'), ('rehabilitation_development', 'Rehabilitation & Development'), ('protection_of_rights', 'Protection of Rights'), ('comprehensive', 'Comprehensive (Multiple Categories)')], help_text='Primary policy category', max_length=30),
        ),
        migrations.AlterField(
            model_name='policyrecommendation',
            name='scope',
            field=models.CharField(choices=[('national', 'National Level'), ('regional', 'Regional Level'), ('provincial', 'Provincial Level'), ('municipal', 'Municipal/City Level'), ('barangay', 'Barangay Level'), ('community', 'Community Level')], help_text='Scope and level of the policy', max_length=15),
        ),
    ]
