# Generated by Django 5.2.7 on 2025-10-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_stafftask_task_context_and_more'),
        ('policy_tracking', '0006_add_secondary_categories_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecommendation',
            name='target_barangay',
            field=models.ForeignKey(blank=True, help_text='Barangay directly referenced by this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_recommendations', to='common.barangay'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='target_municipality',
            field=models.ForeignKey(blank=True, help_text='Municipality or city directly referenced by this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_recommendations', to='common.municipality'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='target_province',
            field=models.ForeignKey(blank=True, help_text='Province directly referenced by this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_recommendations', to='common.province'),
        ),
        migrations.AddField(
            model_name='policyrecommendation',
            name='target_region',
            field=models.ForeignKey(blank=True, help_text='Region directly referenced by this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_recommendations', to='common.region'),
        ),
    ]
