# Generated by Django 4.2.24 on 2025-10-01 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetscenario',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_scenarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
