# Generated by Django 4.2.24 on 2025-10-01 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0016_alter_monitoringentry_milestone_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_central", "0002_alter_budgetscenario_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetApprovalStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("technical_review", "Technical Review"),
                            ("budget_review", "Budget Review"),
                            ("executive_approval", "Executive Approval"),
                            ("enacted", "Enacted"),
                        ],
                        help_text="Approval stage",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("returned", "Returned for Revision"),
                        ],
                        default="pending",
                        help_text="Current status of this approval stage",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this stage was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Reviewer comments and feedback"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved/rejected this stage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ppa",
                    models.ForeignKey(
                        help_text="PPA being approved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_stages",
                        to="monitoring.monitoringentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Approval Stage",
                "verbose_name_plural": "Budget Approval Stages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["ppa", "stage"], name="project_cen_ppa_id_5e4592_idx"
                    ),
                    models.Index(
                        fields=["status", "stage"], name="project_cen_status_41aadd_idx"
                    ),
                    models.Index(
                        fields=["approver", "approved_at"],
                        name="project_cen_approve_d5a864_idx",
                    ),
                ],
                "unique_together": {("ppa", "stage")},
            },
        ),
    ]
