# Generated by Django 5.2.7 on 2025-10-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_eventproxy_projectworkflowproxy_stafftaskproxy"),
        ("project_central", "0003_budgetapprovalstage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="related_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Related project workflow (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_alerts",
                to="common.workitem",
            ),
        ),
        migrations.DeleteModel(
            name="ProjectWorkflow",
        ),
    ]
