# Generated by Django 5.2.7 on 2025-10-12 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget_preparation", "0001_initial"),
        (
            "monitoring",
            "0023_monitoringentry_monitoring_entry_budget_allocation_within_ceiling_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allotment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[
                            (1, "Q1 (Jan-Mar)"),
                            (2, "Q2 (Apr-Jun)"),
                            (3, "Q3 (Jul-Sep)"),
                            (4, "Q4 (Oct-Dec)"),
                        ],
                        help_text="Quarter (1-4)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Allotment amount released",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("released", "Released"),
                            ("partially_utilized", "Partially Utilized"),
                            ("fully_utilized", "Fully Utilized"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Allotment status",
                        max_length=20,
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, help_text="Date allotment was released", null=True
                    ),
                ),
                (
                    "allotment_order_number",
                    models.CharField(
                        blank=True,
                        help_text="Official allotment order number",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or remarks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allotments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_budget",
                    models.ForeignKey(
                        help_text="Program budget this allotment is released from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="budget_preparation.programbudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allotment",
                "verbose_name_plural": "Allotments",
                "db_table": "budget_execution_allotment",
                "ordering": ["program_budget", "quarter"],
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("disbursed_date", models.DateField()),
                ("payee", models.CharField(max_length=255)),
                ("check_number", models.CharField(blank=True, max_length=50)),
                ("voucher_number", models.CharField(blank=True, max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="check",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disbursement",
                "verbose_name_plural": "Disbursements",
                "db_table": "budget_execution_disbursement",
                "ordering": ["-disbursed_date"],
            },
        ),
        migrations.CreateModel(
            name="DisbursementLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disbursement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="budget_execution.disbursement",
                    ),
                ),
                (
                    "monitoring_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursement_line_items",
                        to="monitoring.monitoringentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disbursement Line Item",
                "verbose_name_plural": "Disbursement Line Items",
                "db_table": "budget_execution_disbursement_line_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("obligated_date", models.DateField()),
                (
                    "document_ref",
                    models.CharField(
                        blank=True, help_text="PO/Contract number", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("committed", "Committed"),
                            ("partially_disbursed", "Partially Disbursed"),
                            ("fully_disbursed", "Fully Disbursed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allotment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations",
                        to="budget_execution.allotment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitoring_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obligations",
                        to="monitoring.monitoringentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligation",
                "verbose_name_plural": "Obligations",
                "db_table": "budget_execution_obligation",
                "ordering": ["-obligated_date"],
            },
        ),
        migrations.AddField(
            model_name="disbursement",
            name="obligation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disbursements",
                to="budget_execution.obligation",
            ),
        ),
        migrations.AddIndex(
            model_name="allotment",
            index=models.Index(
                fields=["program_budget", "status"],
                name="budget_exec_program_1f5da3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allotment",
            index=models.Index(
                fields=["quarter"], name="budget_exec_quarter_d4c8bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allotment",
            index=models.Index(
                fields=["release_date"], name="budget_exec_release_1cff69_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="allotment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.01"))),
                name="allotment_positive_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="allotment",
            constraint=models.CheckConstraint(
                condition=models.Q(("quarter__gte", 1), ("quarter__lte", 4)),
                name="allotment_valid_quarter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="allotment",
            unique_together={("program_budget", "quarter")},
        ),
        migrations.AddIndex(
            model_name="disbursementlineitem",
            index=models.Index(
                fields=["disbursement"], name="budget_exec_disburs_9b5b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disbursementlineitem",
            index=models.Index(
                fields=["monitoring_entry"], name="budget_exec_monitor_fa2e8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursementlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.01"))),
                name="disbursement_line_item_positive_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(
                fields=["allotment", "status"], name="budget_exec_allotme_9761f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="obligation",
            index=models.Index(
                fields=["-obligated_date"], name="budget_exec_obligat_bf053c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="obligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.01"))),
                name="obligation_positive_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="disbursement",
            index=models.Index(
                fields=["obligation"], name="budget_exec_obligat_141c46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disbursement",
            index=models.Index(
                fields=["-disbursed_date"], name="budget_exec_disburs_c56f84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.01"))),
                name="disbursement_positive_amount",
            ),
        ),
    ]
