# Generated by Django 5.2.7 on 2025-10-20 05:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_execution', '0002_update_allotment_optional_fields'),
        ('monitoring', '0023_monitoringentry_monitoring_entry_budget_allocation_within_ceiling_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='disbursement',
            options={'ordering': ['-disbursed_at'], 'verbose_name': 'Disbursement', 'verbose_name_plural': 'Disbursements'},
        ),
        migrations.AlterModelOptions(
            name='obligation',
            options={'ordering': ['-obligated_at'], 'verbose_name': 'Obligation', 'verbose_name_plural': 'Obligations'},
        ),
        migrations.RemoveConstraint(
            model_name='allotment',
            name='allotment_positive_amount',
        ),
        migrations.RemoveConstraint(
            model_name='allotment',
            name='allotment_valid_quarter',
        ),
        migrations.RemoveConstraint(
            model_name='disbursement',
            name='disbursement_positive_amount',
        ),
        migrations.RemoveConstraint(
            model_name='obligation',
            name='obligation_positive_amount',
        ),
        migrations.RemoveIndex(
            model_name='allotment',
            name='budget_exec_release_1cff69_idx',
        ),
        migrations.RemoveIndex(
            model_name='disbursement',
            name='budget_exec_disburs_c56f84_idx',
        ),
        migrations.RemoveIndex(
            model_name='obligation',
            name='budget_exec_obligat_bf053c_idx',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='allotment_order_number',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allotment',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='disbursed_date',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='voucher_number',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='document_ref',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='monitoring_entry',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='obligated_date',
        ),
        migrations.AddField(
            model_name='allotment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional release reference or document number', max_length=50),
        ),
        migrations.AddField(
            model_name='allotment',
            name='released_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the allotment was released'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursed_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the disbursement was made'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Optional reference (check/voucher number)', max_length=100),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('void', 'Void')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='obligation',
            name='obligated_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the obligation was recorded'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Allotment amount (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional release notes'),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], help_text='Quarter identifier (Q1–Q4)', max_length=2),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('partially_utilized', 'Partially Utilized'), ('fully_utilized', 'Fully Utilized'), ('cancelled', 'Cancelled')], default='pending', help_text='Allotment release status', max_length=25),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount disbursed (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='obligation',
            field=models.ForeignKey(help_text='Obligation this disbursement fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='budget_execution.obligation'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='allotment',
            field=models.ForeignKey(help_text='Allotment funding this obligation', on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='budget_execution.allotment'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Obligated amount (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional obligation notes'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('obligated', 'Obligated'), ('partially_disbursed', 'Partially Disbursed'), ('fully_disbursed', 'Fully Disbursed'), ('cancelled', 'Cancelled')], default='obligated', help_text='Obligation status', max_length=25),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['status'], name='budget_exec_status_d00ee1_idx'),
        ),
        migrations.AlterModelTable(
            name='allotment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='disbursement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='obligation',
            table=None,
        ),
        migrations.AddField(
            model_name='workitem',
            name='monitoring_entry',
            field=models.ForeignKey(help_text='Linked monitoring entry (PPA)', on_delete=django.db.models.deletion.PROTECT, related_name='execution_work_items', to='monitoring.monitoringentry'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['work_item'], name='budget_exec_work_it_086a51_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['monitoring_entry'], name='budget_exec_monitor_05aa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='budget_exec_status_5af77f_idx'),
        ),
    ]
