# Generated by Django 5.2.7 on 2025-10-20 08:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_execution", "0003_workitem_alter_disbursement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitem",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
