# Generated by Django 5.2.7 on 2025-10-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_barmm_organizations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_code_9d1386_idx',
            old_name='organizatio_code_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_org_typ_43e278_idx',
            old_name='organizatio_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_is_pilo_719cc1_idx',
            old_name='organizatio_is_pilot_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_user_id_9457eb_idx',
            old_name='organizatio_user_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_organiz_e1169f_idx',
            old_name='organizatio_org_role_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='organizatio_user_id_f058b7_idx',
            old_name='organizatio_user_org_idx',
        ),
    ]
