from django.urls import path
from . import views
from communities import data_utils

app_name = 'common'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('communities/', views.communities_home, name='communities_home'),
    path('communities/add/', views.communities_add, name='communities_add'),
    path('communities/add-municipality/', views.communities_add_municipality, name='communities_add_municipality'),
    path('communities/<int:community_id>/', views.communities_view, name='communities_view'),
    path('communities/<int:community_id>/edit/', views.communities_edit, name='communities_edit'),
    path('communities/<int:community_id>/delete/', views.communities_delete, name='communities_delete'),
    path('communities/<int:community_id>/restore/', views.communities_restore, name='communities_restore'),
    path('communities/manage/', views.communities_manage, name='communities_manage'),
    path('communities/managemunicipal/', views.communities_manage_municipal, name='communities_manage_municipal'),
    path('communities/managebarangayobc/', views.communities_manage, name='communities_manage_barangay_obc'),
    path('communities/managemunicipalobc/', views.communities_manage_municipal, name='communities_manage_municipal_obc'),
    path('communities/municipal/<int:coverage_id>/', views.communities_view_municipal, name='communities_view_municipal'),
    path('communities/municipal/<int:coverage_id>/edit/', views.communities_edit_municipal, name='communities_edit_municipal'),
    path('communities/municipal/<int:coverage_id>/delete/', views.communities_delete_municipal, name='communities_delete_municipal'),
    path('communities/municipal/<int:coverage_id>/restore/', views.communities_restore_municipal, name='communities_restore_municipal'),
    path('communities/stakeholders/', views.communities_stakeholders, name='communities_stakeholders'),
    path('locations/centroid/', views.location_centroid, name='location_centroid'),
    path('mana/', views.mana_home, name='mana_home'),
    path('mana/regional/', views.mana_regional_overview, name='mana_regional_overview'),
    path('mana/provincial/', views.mana_provincial_overview, name='mana_provincial_overview'),
    path('mana/provincial/<int:province_id>/', views.mana_provincial_card_detail, name='mana_provincial_card_detail'),
    path('mana/provincial/<int:province_id>/edit/', views.mana_province_edit, name='mana_province_edit'),
    path('mana/provincial/<int:province_id>/delete/', views.mana_province_delete, name='mana_province_delete'),
    path('mana/desk-review/', views.mana_desk_review, name='mana_desk_review'),
    path('mana/survey/', views.mana_survey_module, name='mana_survey_module'),
    path('mana/kii/', views.mana_key_informant_interviews, name='mana_kii'),
    path('mana/playbook/', views.mana_playbook, name='mana_playbook'),
    path('mana/activity-planner/', views.mana_activity_planner, name='mana_activity_planner'),
    path('mana/activity-log/', views.mana_activity_log, name='mana_activity_log'),
    path('mana/activity-processing/', views.mana_activity_processing, name='mana_activity_processing'),
    path('mana/new-assessment/', views.mana_new_assessment, name='mana_new_assessment'),
    path('mana/manage-assessments/', views.mana_manage_assessments, name='mana_manage_assessments'),
    path('mana/geographic-data/', views.mana_geographic_data, name='mana_geographic_data'),
    path('coordination/', views.coordination_home, name='coordination_home'),
    path('coordination/organizations/', views.coordination_organizations, name='coordination_organizations'),
    path('coordination/organizations/add/', views.organization_create, name='coordination_organization_add'),
    path('coordination/organizations/<uuid:organization_id>/edit/', views.organization_edit, name='coordination_organization_edit'),
    path('coordination/organizations/<uuid:organization_id>/delete/', views.organization_delete, name='coordination_organization_delete'),
    path('coordination/organizations/<uuid:organization_id>/', views.organization_detail, name='coordination_organization_detail'),
    path('coordination/partnerships/', views.coordination_partnerships, name='coordination_partnerships'),
    path('coordination/partnerships/add/', views.partnership_create, name='coordination_partnership_add'),
    path('coordination/partnerships/<uuid:partnership_id>/', views.partnership_detail, name='coordination_partnership_view'),
    path('coordination/partnerships/<uuid:partnership_id>/edit/', views.partnership_update, name='coordination_partnership_edit'),
    path('coordination/partnerships/<uuid:partnership_id>/delete/', views.partnership_delete, name='coordination_partnership_delete'),
    path('coordination/events/add/', views.event_create, name='coordination_event_add'),
    path('coordination/events/', views.coordination_events, name='coordination_events'),
    path('coordination/calendar/', views.coordination_calendar, name='coordination_calendar'),
    path('coordination/activities/add/', views.coordination_activity_create, name='coordination_activity_add'),
    path('coordination/view-all/', views.coordination_view_all, name='coordination_view_all'),
    path('recommendations/', views.recommendations_home, name='recommendations_home'),
    path('recommendations/new/', views.recommendations_new, name='recommendations_new'),
    path('recommendations/manage/', views.recommendations_manage, name='recommendations_manage'),
    path('recommendations/area/<str:area_slug>/', views.recommendations_by_area, name='recommendations_by_area'),
    path('oobc-management/', views.oobc_management_home, name='oobc_management_home'),
    path('oobc-management/staff/', views.staff_management, name='staff_management'),
    path('oobc-management/planning-budgeting/', views.planning_budgeting, name='planning_budgeting'),

    # Data Import/Export/Report URLs
    path('communities/import/', data_utils.import_communities_csv, name='import_communities'),
    path('communities/export/', data_utils.export_communities, name='export_communities'),
    path('communities/report/', data_utils.generate_obc_report, name='generate_obc_report'),
    path('data-guidelines/', data_utils.data_guidelines, name='data_guidelines'),
    
    path('', views.dashboard, name='home'),  # Default to dashboard
]
