# Generated by Django 4.2.16 on 2025-09-22 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipal_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalobcprofile',
            name='last_reported_by',
            field=models.ForeignKey(blank=True, help_text='User who last submitted municipal reported metrics.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipal_profiles_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipalobcprofile',
            name='reported_signatories',
            field=models.JSONField(blank=True, default=list, help_text='List of municipal signatories acknowledging the reported data.'),
        ),
        migrations.AddField(
            model_name='municipalobcprofile',
            name='reported_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned for Revision')], default='draft', help_text='Workflow status for the latest municipal submission.', max_length=20),
        ),
        migrations.AddField(
            model_name='municipalobcprofile',
            name='reported_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the municipal report was submitted for review.', null=True),
        ),
        migrations.AddField(
            model_name='municipalobcprofilehistory',
            name='diff',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
