# Generated by Django 4.2.21 on 2025-05-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Official region code (e.g., IX, XII)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official region name", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional region description or notes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this region is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "common_region",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Official province code", max_length=10, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official province name", max_length=255
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True, help_text="Provincial capital city", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this province is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        help_text="Parent region",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinces",
                        to="common.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "common_province",
                "ordering": ["region__code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Official municipality/city code",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official municipality/city name", max_length=255
                    ),
                ),
                (
                    "municipality_type",
                    models.CharField(
                        choices=[
                            ("municipality", "Municipality"),
                            ("city", "City"),
                            ("component_city", "Component City"),
                            ("independent_city", "Independent City"),
                        ],
                        default="municipality",
                        help_text="Type of local government unit",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this municipality is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Parent province",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipalities",
                        to="common.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
                "db_table": "common_municipality",
                "ordering": ["province__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Barangay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Official barangay code", max_length=10, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official barangay name", max_length=255
                    ),
                ),
                (
                    "is_urban",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this barangay is classified as urban",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this barangay is active in the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "municipality",
                    models.ForeignKey(
                        help_text="Parent municipality",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barangays",
                        to="common.municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barangay",
                "verbose_name_plural": "Barangays",
                "db_table": "common_barangay",
                "ordering": ["municipality__name", "name"],
            },
        ),
    ]
