# Generated by Django 4.2.24 on 2025-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_region_province_municipality_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='population_total',
            field=models.PositiveIntegerField(blank=True, help_text='Total population based on latest PSA census', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='population_total',
            field=models.PositiveIntegerField(blank=True, help_text='Total population based on latest PSA census', null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='population_total',
            field=models.PositiveIntegerField(blank=True, help_text='Total population based on latest PSA census', null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='code',
            field=models.CharField(help_text='Official barangay code', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(help_text='Official municipality/city code', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(help_text='Official province code', max_length=64, unique=True),
        ),
    ]
