# Generated by Django 4.2.24 on 2025-09-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_ensure_population_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangay",
            name="boundary_geojson",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON polygon defining the barangay boundary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="barangay",
            name="bounding_box",
            field=models.JSONField(
                blank=True,
                help_text="Bounding box [min_lng, min_lat, max_lng, max_lat]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="barangay",
            name="center_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Geographic center point [longitude, latitude]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="boundary_geojson",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON polygon defining the municipality boundary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="bounding_box",
            field=models.JSONField(
                blank=True,
                help_text="Bounding box [min_lng, min_lat, max_lng, max_lat]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="center_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Geographic center point [longitude, latitude]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="boundary_geojson",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON polygon defining the province boundary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="bounding_box",
            field=models.JSONField(
                blank=True,
                help_text="Bounding box [min_lng, min_lat, max_lng, max_lat]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="center_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Geographic center point [longitude, latitude]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="boundary_geojson",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON polygon defining the region boundary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="bounding_box",
            field=models.JSONField(
                blank=True,
                help_text="Bounding box [min_lng, min_lat, max_lng, max_lat]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="center_coordinates",
            field=models.JSONField(
                blank=True,
                help_text="Geographic center point [longitude, latitude]",
                null=True,
            ),
        ),
    ]
