# Generated by Django 4.2.24 on 2025-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_staff_profile_and_development"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="cross_functional_partners",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="deliverables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="job_documents_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="job_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="key_result_areas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="major_functions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="plantilla_item_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="position_classification",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="qualification_competency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="qualification_education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="qualification_eligibility",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="qualification_experience",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="qualification_training",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="reports_to",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="salary_grade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="salary_step",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="supervision_lines",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="staffdevelopmentplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trainingenrollment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
