# Generated by Django 4.2.24 on 2025-09-28 12:13

from django.conf import settings
from django.db import migrations, models


def forwards_migrate_assignees(apps, schema_editor):
    StaffTask = apps.get_model('common', 'StaffTask')
    through_model = StaffTask.assignees.through
    pending = []
    for task_id, user_id in StaffTask.objects.exclude(assignee_id__isnull=True).values_list('id', 'assignee_id'):
        pending.append(through_model(stafftask_id=task_id, user_id=user_id))
    if pending:
        through_model.objects.bulk_create(pending, ignore_conflicts=True)


def backwards_migrate_assignees(apps, schema_editor):
    StaffTask = apps.get_model('common', 'StaffTask')
    through_model = StaffTask.assignees.through
    for task_id in StaffTask.objects.values_list('id', flat=True):
        user_id = (
            through_model.objects.filter(stafftask_id=task_id)
            .values_list('user_id', flat=True)
            .first()
        )
        if user_id is not None:
            StaffTask.objects.filter(pk=task_id).update(assignee_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_stafftask_board_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftask',
            options={'ordering': ['board_position', 'due_date', '-priority', 'title']},
        ),
        migrations.AddField(
            model_name='stafftask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_migrate_assignees, backwards_migrate_assignees),
        migrations.RemoveField(
            model_name='stafftask',
            name='assignee',
        ),
    ]
