# Generated by Django 4.2.24 on 2025-09-28 14:15

from django.db import migrations, models


def forwards_migrate_teams(apps, schema_editor):
    """Migrate existing team assignments to the new teams many-to-many field."""
    StaffTask = apps.get_model('common', 'StaffTask')
    through_model = StaffTask.teams.through
    pending = []
    for task_id, team_id in StaffTask.objects.exclude(team_id__isnull=True).values_list('id', 'team_id'):
        pending.append(through_model(stafftask_id=task_id, staffteam_id=team_id))
    if pending:
        through_model.objects.bulk_create(pending, ignore_conflicts=True)


def backwards_migrate_teams(apps, schema_editor):
    """Migrate teams back to single team field for rollback."""
    StaffTask = apps.get_model('common', 'StaffTask')
    through_model = StaffTask.teams.through
    for task_id in StaffTask.objects.values_list('id', flat=True):
        team_id = (
            through_model.objects.filter(stafftask_id=task_id)
            .values_list('staffteam_id', flat=True)
            .first()
        )
        if team_id is not None:
            StaffTask.objects.filter(pk=task_id).update(team_id=team_id)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_stafftask_options_remove_stafftask_assignee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftask",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="common.staffteam"
            ),
        ),
        migrations.RunPython(forwards_migrate_teams, backwards_migrate_teams),
        migrations.RemoveField(
            model_name="stafftask",
            name="team",
        ),
    ]
