# Generated by Django 4.2.24 on 2025-10-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_central', '0001_initial'),
        ('monitoring', '0011_monitoringentry_approval_history_and_more'),
        ('common', '0015_migrate_monitoring_task_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Whether this task was automatically generated by workflow automation'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='linked_ppa',
            field=models.ForeignKey(blank=True, help_text='Link task to PPA (for workflow tasks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='linked_workflow',
            field=models.ForeignKey(blank=True, help_text='Link task to project workflow', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_central.projectworkflow'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='workflow_stage',
            field=models.CharField(blank=True, help_text='Workflow stage this task belongs to', max_length=30),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='domain',
            field=models.CharField(blank=True, choices=[('general', 'General Staff Task'), ('communities', 'Community Management'), ('mana', 'MANA Assessment'), ('coordination', 'Coordination & Partnerships'), ('monitoring', 'Monitoring & Evaluation'), ('policy', 'Policy Development'), ('services', 'Service Delivery'), ('municipal', 'Municipal Profiles'), ('data', 'Data Management'), ('ai', 'AI Operations'), ('project_central', 'Project Management')], default='general', help_text='Domain/module this task belongs to', max_length=30),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='domain',
            field=models.CharField(choices=[('general', 'General Staff Task'), ('communities', 'Community Management'), ('mana', 'MANA Assessment'), ('coordination', 'Coordination & Partnerships'), ('monitoring', 'Monitoring & Evaluation'), ('policy', 'Policy Development'), ('services', 'Service Delivery'), ('municipal', 'Municipal Profiles'), ('data', 'Data Management'), ('ai', 'AI Operations'), ('project_central', 'Project Management')], help_text='Domain this template applies to', max_length=30),
        ),
    ]
