# Generated by Django 4.2.24 on 2025-10-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0016_stafftask_auto_generated_stafftask_linked_ppa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarnotification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='calendarnotification',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarresourcebooking',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='calendarresourcebooking',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
