# Generated by Django 5.2.7 on 2025-10-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_alter_calendarnotification_content_type_and_more"),
        ("communities", "0026_communityevent"),
        ("coordination", "0010_eventattendance"),
        ("data_imports", "0001_initial"),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0016_alter_monitoringentry_milestone_dates"),
        ("municipal_profiles", "0002_municipalobcprofile_last_reported_by_and_more"),
        ("policy_tracking", "0003_policyimplementationmilestone"),
        ("project_central", "0003_budgetapprovalstage"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftask",
            name="task_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standalone", "Standalone Task"),
                    ("project", "Project Task"),
                    ("activity", "Activity/Event Task"),
                    ("project_activity", "Project Activity Task"),
                ],
                default="standalone",
                help_text="Context in which this task exists (standalone, project, activity, or both)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="stafftask",
            index=models.Index(
                fields=["task_context", "status"], name="common_staf_task_co_f7fed1_idx"
            ),
        ),
    ]
