# Generated by Django 5.2.7 on 2025-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_workitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktemplateitem",
            name="template",
        ),
        migrations.DeleteModel(
            name="StaffTask",
        ),
        migrations.DeleteModel(
            name="TaskTemplate",
        ),
        migrations.DeleteModel(
            name="TaskTemplateItem",
        ),
    ]
