# Generated by Django 5.2.7 on 2025-10-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_add_model_validation_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventProxy",
            fields=[],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.workitem",),
        ),
        migrations.CreateModel(
            name="ProjectWorkflowProxy",
            fields=[],
            options={
                "verbose_name": "Project Workflow",
                "verbose_name_plural": "Project Workflows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.workitem",),
        ),
        migrations.CreateModel(
            name="StaffTaskProxy",
            fields=[],
            options={
                "verbose_name": "Staff Task",
                "verbose_name_plural": "Staff Tasks",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.workitem",),
        ),
    ]
