# Generated by Django 5.2.7 on 2025-10-05 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_workitem_explicit_fks'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('mana', '0021_add_needvote_model'),
        ('monitoring', '0019_rename_workitem_indexes'),
        ('policy_tracking', '0007_policyrecommendation_target_barangay_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workitem',
            new_name='wi_rel_assessment_idx',
            old_name='workitem_related_assessment_idx',
        ),
        migrations.RenameIndex(
            model_name='workitem',
            new_name='wi_rel_policy_idx',
            old_name='workitem_related_policy_idx',
        ),
        migrations.AddField(
            model_name='workitem',
            name='actual_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual expenditure recorded (PHP)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated to this work item (PHP)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='budget_notes',
            field=models.TextField(blank=True, help_text='Budget-related notes and explanations'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='related_ppa',
            field=models.ForeignKey(blank=True, help_text='Related MOA PPA (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='monitoring.monitoringentry'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['related_ppa'], name='wi_rel_ppa_idx'),
        ),
    ]
