# Generated by Django 5.2.7 on 2025-10-06 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0024_rename_workitem_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_message",
                    models.TextField(help_text="User's natural language question"),
                ),
                (
                    "assistant_response",
                    models.TextField(help_text="Assistant's response"),
                ),
                (
                    "intent",
                    models.CharField(
                        help_text="Classified intent (data_query, analysis, help, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Intent classification confidence (0.0-1.0)",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Topic of conversation (communities, mana, policies, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Detected entities in the message",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session ID for grouping conversations",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "common_chat_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="common_chat_user_id_78ce39_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="common_chat_session_1faed9_idx",
                    ),
                    models.Index(fields=["topic"], name="common_chat_topic_7cac25_idx"),
                ],
            },
        ),
    ]
