# Generated by Django 5.2.7 on 2025-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0025_chatmessage"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0020_monitoringentry_auto_sync_progress_and_more"),
        ("policy_tracking", "0007_policyrecommendation_target_barangay_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["tree_id", "lft", "rght"], name="wi_tree_traversal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["parent_id"], name="wi_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["is_calendar_visible", "start_date", "due_date"],
                name="wi_calendar_idx",
            ),
        ),
    ]
