# Generated by Django 5.2.7 on 2025-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_work_item_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('oobc_executive', 'OOBC Executive'), ('oobc_staff', 'OOBC Staff'), ('cm_office', 'Chief Minister Office'), ('bmoa', 'BARMM Ministry/Agency/Office'), ('lgu', 'Local Government Unit'), ('nga', 'National Government Agency'), ('community_leader', 'Community Leader'), ('researcher', 'Assessment Coordinator/Researcher')], help_text='Type of user based on organization role', max_length=20),
        ),
    ]
