# Generated by Django 5.2.7 on 2025-10-06 16:49

from django.db import migrations


def promote_to_executive(apps, schema_editor):
    User = apps.get_model('common', 'User')

    updates = {
        'noron.oobc': {
            'user_type': 'oobc_executive',
        },
        'qurash.oobc': {
            'user_type': 'oobc_executive',
            'first_name': 'Quraish',
        },
    }

    for username, fields in updates.items():
        User.objects.filter(username=username).update(**fields)


def demote_to_staff(apps, schema_editor):
    User = apps.get_model('common', 'User')

    revert = {
        'noron.oobc': {
            'user_type': 'oobc_staff',
        },
        'qurash.oobc': {
            'user_type': 'oobc_staff',
            'first_name': 'Qurash',
        },
    }

    for username, fields in revert.items():
        User.objects.filter(username=username).update(**fields)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_user_user_type'),
    ]

    operations = [
        migrations.RunPython(promote_to_executive, demote_to_staff),
    ]
