# Generated by Django 5.2.7 on 2025-10-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0028_promote_executives"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("coordination", "0013_add_model_validation_constraints"),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0020_monitoringentry_auto_sync_progress_and_more"),
        ("policy_tracking", "0007_policyrecommendation_target_barangay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="implementing_moa",
            field=models.ForeignKey(
                blank=True,
                help_text="Implementing MOA organization (denormalized for filtering). Auto-populated from PPA's implementing_moa field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moa_work_items",
                to="coordination.organization",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="ppa_category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Category from related PPA (denormalized for performance). Choices: moa_ppa, oobc_ppa, obc_request. Auto-populated from PPA.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["ppa_category"], name="wi_ppa_category_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["implementing_moa"], name="wi_implementing_moa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["ppa_category", "implementing_moa"], name="wi_moa_filter_idx"
            ),
        ),
    ]
