# Generated by Django 5.2.7 on 2025-10-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0030_backfill_work_item_isolation_data"),
        ("coordination", "0013_add_model_validation_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="moa_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="MOA organization this user belongs to (for MOA staff only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moa_staff_users",
                to="coordination.organization",
            ),
        ),
    ]
