# Generated by Django 5.2.7 on 2025-10-09 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0033_link_sibling_related_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="moa_first_level_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has been endorsed by their MOA/NGA/LGU focal person",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="moa_first_level_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of focal person endorsement", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="moa_first_level_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Focal person who provided the first-level endorsement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moa_first_level_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
