# Generated by Django 5.2.7 on 2025-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_user_moa_first_level_approved_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarresource",
            options={
                "ordering": ["resource_type", "name"],
                "verbose_name": "Calendar Resource",
                "verbose_name_plural": "Calendar Resources",
            },
        ),
        migrations.RemoveField(
            model_name="calendarresource",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="calendarresource",
            name="cost_per_use",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per use (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarresource",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
