# Generated by Django 5.2.7 on 2025-10-11 05:53

from django.db import migrations, models


def set_default_activity_category(apps, schema_editor):
    WorkItem = apps.get_model("common", "WorkItem")
    WorkItem.objects.filter(
        work_type__in=["activity", "sub_activity"], activity_category__isnull=True
    ).update(activity_category="coordination")


def unset_activity_category(apps, schema_editor):
    WorkItem = apps.get_model("common", "WorkItem")
    WorkItem.objects.filter(activity_category="coordination").update(
        activity_category=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0035_alter_calendarresource_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("coordination", "0014_coordinationnote"),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0022_monitoringentry_beneficiary_demographics_and_more"),
        ("policy_tracking", "0007_policyrecommendation_target_barangay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="activity_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordination", "Coordination Activity"),
                    ("ppa", "PPA Activity"),
                    ("office", "Office Activity"),
                ],
                db_index=True,
                help_text="Category for activity work items (coordination, PPA, office).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["activity_category"], name="wi_activity_category_idx"
            ),
        ),
        migrations.RunPython(
            set_default_activity_category,
            reverse_code=unset_activity_category,
        ),
    ]
