# Generated by Django 4.2.24 on 2025-09-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0004_partnership_partnershipsignatory_and_more"),
        ("common", "0004_ensure_population_columns"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringentry",
            name="budget_obc_allocation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Portion of the budget allocated specifically for OBCs",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="coverage_barangay",
            field=models.ForeignKey(
                blank=True,
                help_text="Barangay covered by the PPA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_entries",
                to="common.barangay",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="coverage_municipality",
            field=models.ForeignKey(
                blank=True,
                help_text="Municipality covered by the PPA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_entries",
                to="common.municipality",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="coverage_province",
            field=models.ForeignKey(
                blank=True,
                help_text="Province covered by the PPA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_entries",
                to="common.province",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="coverage_region",
            field=models.ForeignKey(
                blank=True,
                help_text="Region covered by the PPA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_entries",
                to="common.region",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="implementing_moa",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary MOA implementing the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="implemented_monitoring_entries",
                to="coordination.organization",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="obc_slots",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of slots reserved for OBCs", null=True
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="obcs_benefited",
            field=models.TextField(
                blank=True,
                help_text="Narrative describing OBC groups that have benefited",
            ),
        ),
        migrations.AddField(
            model_name="monitoringentry",
            name="total_slots",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total number of beneficiary slots", null=True
            ),
        ),
    ]
