# Generated by Django 4.2.24 on 2025-09-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0004_partnership_partnershipsignatory_and_more"),
        ("monitoring", "0002_monitoringentry_budget_obc_allocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringentry",
            name="implementing_moa",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary MOA implementing the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="implemented_monitoring_entries",
                to="coordination.organization",
                verbose_name="Implementing MOA",
            ),
        ),
    ]
