# Generated by Django 4.2.24 on 2025-10-01 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0004_monitoringentry_appropriation_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEntryWorkflowDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title or description', max_length=255)),
                ('document_type', models.CharField(choices=[('budget_call', 'Budget Call Memorandum'), ('submission', 'Submission Form'), ('hearing_notes', 'Technical Hearing Notes'), ('approval', 'Approval Letter'), ('aip_form', 'AIP Form / Template'), ('supporting', 'Supporting Document'), ('other', 'Other')], default='supporting', help_text='Type of document for categorization', max_length=32)),
                ('file', models.FileField(help_text='Upload document file (PDF, Word, Excel, etc.)', upload_to='monitoring/workflow_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes (auto-populated)', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes or context for this document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_workflow_documents', to=settings.AUTH_USER_MODEL)),
                ('workflow_stage', models.ForeignKey(help_text='Parent workflow stage', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='monitoring.monitoringentryworkflowstage')),
            ],
            options={
                'verbose_name': 'Workflow Document',
                'verbose_name_plural': 'Workflow Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
