# Generated by Django 4.2.24 on 2025-10-01 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0005_monitoringentryworkflowdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEntryTaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead / Primary Responsible'), ('contributor', 'Contributor / Supporting'), ('reviewer', 'Reviewer / Quality Check'), ('approver', 'Approver / Decision Maker'), ('monitor', 'Monitor / Observer')], default='contributor', help_text='Role in this assignment', max_length=20)),
                ('task_title', models.CharField(help_text='Specific task or responsibility', max_length=255)),
                ('task_description', models.TextField(blank=True, help_text='Detailed instructions or context')),
                ('status', models.CharField(choices=[('pending', 'Pending / Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked / Needs Input'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this assignment', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Actual completion timestamp', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level for this task', max_length=10)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated effort in hours', max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual effort expended', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, help_text='Progress notes or blockers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_monitoring_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Staff member assigned to this task', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(help_text='Parent monitoring entry / PPA', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='monitoring.monitoringentry')),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ['due_date', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='monitoring__assigne_32c68a_idx'), models.Index(fields=['entry', 'role'], name='monitoring__entry_i_4b1de0_idx'), models.Index(fields=['due_date'], name='monitoring__due_dat_8b6d90_idx')],
            },
        ),
    ]
