# Generated by Django 4.2.24 on 2025-10-01 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_tracking', '0003_policyimplementationmilestone'),
        ('mana', '0020_need_budget_inclusion_date_need_community_votes_and_more'),
        ('monitoring', '0006_monitoringentrytaskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringentry',
            name='implementing_policies',
            field=models.ManyToManyField(blank=True, help_text='Policy recommendations this PPA implements', related_name='implementing_ppas', to='policy_tracking.policyrecommendation'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='needs_addressed',
            field=models.ManyToManyField(blank=True, help_text='Community needs this PPA addresses', related_name='implementing_ppas', to='mana.need'),
        ),
        migrations.AlterField(
            model_name='monitoringentry',
            name='related_policy',
            field=models.ForeignKey(blank=True, help_text='Policy recommendation informing this entry (DEPRECATED: use implementing_policies instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_entries', to='policy_tracking.policyrecommendation'),
        ),
    ]
