# Generated by Django 4.2.24 on 2025-10-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0010_monitoringentry_cost_effectiveness_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringentry',
            name='approval_history',
            field=models.JSONField(default=list, help_text='Complete history of approval stages with timestamps, reviewers, and comments'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='General notes about the approval process'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('technical_review', 'Technical Review'), ('budget_review', 'Budget Review'), ('stakeholder_consultation', 'Stakeholder Consultation'), ('executive_approval', 'Executive Approval'), ('approved', 'Approved'), ('enacted', 'Enacted'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current status in the budget approval workflow', max_length=30),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='budget_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the budget allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approved_ppas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='executive_approved_by',
            field=models.ForeignKey(blank=True, help_text='Executive who gave final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_approved_ppas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Reason for rejection (if approval_status is 'rejected')"),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed technical review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technically_reviewed_ppas', to=settings.AUTH_USER_MODEL),
        ),
    ]
