# Generated by Django 4.2.24 on 2025-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0015_remove_monitoringentrytaskassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringentry",
            name="milestone_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured milestone entries: [{date: 2025-10-15, title: Technical hearing, status: upcoming}]",
            ),
        ),
    ]
