# Generated by Django 5.2.7 on 2025-10-05 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_add_model_validation_constraints"),
        ("communities", "0028_clear_municipal_estimated_population"),
        ("coordination", "0012_add_model_validation_constraints"),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0016_alter_monitoringentry_milestone_dates"),
        ("policy_tracking", "0007_policyrecommendation_target_barangay_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringentry",
            name="related_event",
        ),
        migrations.AddConstraint(
            model_name="monitoringentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress__gte", 0), ("progress__lte", 100)),
                name="monitoring_entry_valid_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_end_date__gte", models.F("start_date")),
                    ("start_date__isnull", True),
                    ("target_end_date__isnull", True),
                    _connector="OR",
                ),
                name="monitoring_entry_valid_date_range",
            ),
        ),
    ]
