# Generated by Django migration for MonitoringEntry WorkItem Integration
# This migration adds WorkItem integration fields to MonitoringEntry model
# allowing PPAs to optionally create and sync with project WorkItems.
#
# Key Features:
# - OneToOne relationship to WorkItem for project execution tracking
# - Optional WorkItem tracking toggle (default: disabled for backward compatibility)
# - Budget distribution policy for multi-phase projects
# - Auto-sync flags for progress and status updates
#
# See: docs/improvements/WORKITEM_ENHANCEMENTS_SUMMARY.md

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_workitem'),  # WorkItem model must exist
        ('monitoring', '0017_add_model_validation_constraints'),
    ]

    operations = [
        # Add OneToOne relationship to WorkItem
        migrations.AddField(
            model_name='monitoringentry',
            name='execution_project',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ppa_entry',
                to='common.workitem',
                help_text='Optional WorkItem for tracking project execution tasks and milestones',
            ),
        ),

        # Add WorkItem tracking toggle
        migrations.AddField(
            model_name='monitoringentry',
            name='enable_workitem_tracking',
            field=models.BooleanField(
                default=False,
                help_text='Enable automatic WorkItem creation and synchronization for this PPA',
            ),
        ),

        # Add budget distribution policy
        migrations.AddField(
            model_name='monitoringentry',
            name='budget_distribution_policy',
            field=models.CharField(
                blank=True,
                max_length=20,
                choices=[
                    ('equal', 'Equal Distribution'),
                    ('weighted', 'Weighted by Duration'),
                    ('manual', 'Manual Assignment'),
                ],
                help_text='How to distribute PPA budget across WorkItem phases (when enabled)',
            ),
        ),

        # Add auto-sync progress flag
        migrations.AddField(
            model_name='monitoringentry',
            name='auto_sync_progress',
            field=models.BooleanField(
                default=True,
                help_text='Automatically sync progress from WorkItem completion to PPA progress field',
            ),
        ),

        # Add auto-sync status flag
        migrations.AddField(
            model_name='monitoringentry',
            name='auto_sync_status',
            field=models.BooleanField(
                default=True,
                help_text='Automatically sync status changes between WorkItem and PPA',
            ),
        ),

        # Add database index for efficient filtering
        migrations.AddIndex(
            model_name='monitoringentry',
            index=models.Index(
                fields=['enable_workitem_tracking'],
                name='monitoring_workitem_enabled_idx',
            ),
        ),
    ]
