# Generated by Django 5.2.7 on 2025-10-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_add_workitem_integration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monitoringentry',
            name='monitoring_workitem_enabled_idx',
        ),
        migrations.RemoveField(
            model_name='monitoringentry',
            name='auto_sync_progress',
        ),
        migrations.RemoveField(
            model_name='monitoringentry',
            name='auto_sync_status',
        ),
        migrations.RemoveField(
            model_name='monitoringentry',
            name='budget_distribution_policy',
        ),
        migrations.RemoveField(
            model_name='monitoringentry',
            name='enable_workitem_tracking',
        ),
        migrations.RemoveField(
            model_name='monitoringentry',
            name='execution_project',
        ),
        migrations.AlterField(
            model_name='monitoringentry',
            name='approval_history',
            field=models.JSONField(blank=True, default=list, help_text='Complete history of approval stages with timestamps, reviewers, and comments'),
        ),
    ]
