# Generated by Django 5.2.7 on 2025-10-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_rename_workitem_indexes'),
        ('monitoring', '0019_rename_workitem_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringentry',
            name='auto_sync_progress',
            field=models.BooleanField(default=True, help_text='Automatically sync progress from execution project'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='auto_sync_status',
            field=models.BooleanField(default=True, help_text='Automatically sync status from execution project'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='budget_distribution_policy',
            field=models.CharField(blank=True, choices=[('equal', 'Equal'), ('weighted', 'Weighted'), ('manual', 'Manual')], help_text='Policy for distributing budget across child work items', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='enable_workitem_tracking',
            field=models.BooleanField(default=False, help_text='Enable WorkItem-based execution tracking for this PPA'),
        ),
        migrations.AddField(
            model_name='monitoringentry',
            name='execution_project',
            field=models.OneToOneField(blank=True, help_text='Root WorkItem project for execution tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppa_source', to='common.workitem'),
        ),
    ]
