# Generated by Django 5.2.7 on 2025-10-11 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0036_workitem_activity_category_and_more"),
        ("communities", "0028_clear_municipal_estimated_population"),
        (
            "coordination",
            "0015_organization_barangay_organization_municipality_and_more",
        ),
        ("mana", "0021_add_needvote_model"),
        ("monitoring", "0022_monitoringentry_beneficiary_demographics_and_more"),
        ("policy_tracking", "0007_policyrecommendation_target_barangay_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="monitoringentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_ceiling__isnull", True),
                    ("budget_allocation__isnull", True),
                    ("budget_allocation__lte", models.F("budget_ceiling")),
                    _connector="OR",
                ),
                name="monitoring_entry_budget_allocation_within_ceiling",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_allocation__isnull", True),
                    ("budget_obc_allocation__isnull", True),
                    ("budget_obc_allocation__lte", models.F("budget_allocation")),
                    _connector="OR",
                ),
                name="monitoring_entry_obc_allocation_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoringentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_slots__isnull", True),
                    ("obc_slots__isnull", True),
                    ("obc_slots__lte", models.F("total_slots")),
                    _connector="OR",
                ),
                name="monitoring_entry_obc_slots_within_total",
            ),
        ),
    ]
